<?php
declare(strict_types=1);
$config=require __DIR__.'/config.php';date_default_timezone_set('Asia/Kolkata');
$maintenanceFile=__DIR__.'/data/maintenance.flag';
if(PHP_SAPI!=='cli'&&is_file($maintenanceFile)){
    if(!headers_sent()){http_response_code(503);header('Retry-After: 60');header('Cache-Control: no-store');header('Content-Type: text/html; charset=utf-8');}
    exit('<!doctype html><html><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Udaan · Maintenance</title><body style="font-family:system-ui;margin:0;display:grid;place-items:center;min-height:100vh;background:#f4f1e9;color:#171914"><main style="max-width:560px;padding:32px"><small>UDAAN LIVE</small><h1>Security maintenance in progress.</h1><p>Please reopen Udaan shortly.</p></main></body></html>');
}
$trustProxy=(bool)($config['trust_proxy_headers']??false);$forwardedProto=strtolower(trim(explode(',',(string)($_SERVER['HTTP_X_FORWARDED_PROTO']??''))[0]));$https=($trustProxy&&$forwardedProto==='https')||(!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off');$doc=str_replace('\\','/',realpath($_SERVER['DOCUMENT_ROOT']??'')?:'');$app=str_replace('\\','/',realpath(__DIR__)?:__DIR__);$cookiePath='/';if($doc!==''&&str_starts_with($app,rtrim($doc,'/'))){$rel=trim(substr($app,strlen(rtrim($doc,'/'))),'/');$cookiePath=$rel===''?'/':'/'.$rel.'/';}
ini_set('session.use_strict_mode','1');ini_set('session.use_only_cookies','1');session_name('UDAANLIVESESSID');session_set_cookie_params(['lifetime'=>0,'path'=>$cookiePath,'secure'=>$https,'httponly'=>true,'samesite'=>'Lax']);if(session_status()!==PHP_SESSION_ACTIVE)session_start();if(!isset($_SESSION['udaan_live'])||!is_array($_SESSION['udaan_live']))$_SESSION['udaan_live']=[];
require_once __DIR__.'/lib/helpers.php';require_once __DIR__.'/lib/Player.php';require_once __DIR__.'/lib/Store.php';require_once __DIR__.'/lib/Social.php';require_once __DIR__.'/lib/Competition.php';require_once __DIR__.'/lib/Performance.php';require_once __DIR__.'/lib/DailyReadiness.php';require_once __DIR__.'/lib/Fit.php';require_once __DIR__.'/lib/Momentum.php';require_once __DIR__.'/lib/Mission.php';require_once __DIR__.'/lib/Coach.php';require_once __DIR__.'/lib/ContentImport.php';require_once __DIR__.'/lib/ContentPacks.php';
set_exception_handler(function(Throwable $e):void{$ref=strtoupper(substr(bin2hex(random_bytes(6)),0,10));$line=date('c')." [$ref] ".get_class($e).': '.$e->getMessage().' in '.$e->getFile().':'.$e->getLine()."\n".$e->getTraceAsString()."\n\n";@file_put_contents(__DIR__.'/data/php-error.log',$line,FILE_APPEND|LOCK_EX);if(!headers_sent()){http_response_code(500);header('Content-Type: text/html; charset=utf-8');header('Cache-Control: no-store');}echo '<!doctype html><html><meta name="viewport" content="width=device-width,initial-scale=1"><meta charset="utf-8"><title>Udaan · Temporary error</title><style>body{margin:0;background:#f4f1e9;color:#171914;font-family:system-ui;display:grid;place-items:center;min-height:100vh;padding:24px}.c{max-width:600px}h1{font:400 48px/1 Georgia,serif}p{color:#666;line-height:1.6}code{font-size:12px}</style><div class="c"><small>UDAAN LIVE</small><h1>This session hit a temporary error.</h1><p>Please reopen the room link or scan the QR again. Error reference <code>'.htmlspecialchars($ref,ENT_QUOTES,'UTF-8').'</code>.</p></div></html>';});
$store=new TempStore($config,__DIR__.'/data/rooms');if($store->redisRequired()&&!$store->redisConnected())throw new RuntimeException('Required Redis runtime is unavailable. Check /ready for deployment diagnostics.');
function new_room(string $title='Future India · Live Learning',int $journeyLength=27):array{global $config;$id=room_id();$length=normalize_journey_length($journeyLength);return ['id'=>$id,'code'=>$id,'title'=>$title,'journey_length'=>$length,'state_token'=>rand_id(24),'created_at'=>now_iso(),'expires_at'=>date(DATE_ATOM,time()+$config['room_ttl_seconds']),'participants'=>[],'signals'=>['future_topics'=>[]],'commitments'=>[]];}
function room_public_state(array $room):array{$participants=array_values(is_array($room['participants']??null)?$room['participants']:[]);$verified=array_values(array_filter($participants,fn($p)=>is_array($p)&&!empty($p['verified_at'])));usort($verified,fn($a,$b)=>(($b['score']??0)<=>($a['score']??0))?:strcmp((string)($a['joined_at']??''),(string)($b['joined_at']??'')));$ladder=[];foreach(array_slice($verified,0,12)as$i=>$p)$ladder[]=['rank'=>$i+1,'nickname'=>(string)($p['nickname']??'Learner'),'score'=>(int)($p['score']??0),'completed'=>(bool)($p['completed']??false),'progress'=>(int)($p['answered_count']??0),'total'=>(int)($p['journey_total']??($room['journey_length']??27))];$future=[];foreach(($room['signals']['future_topics']??[])as$topic)if(is_string($topic))$future[$topic]=($future[$topic]??0)+1;$topFuture=null;if($future){arsort($future);$topFuture=array_key_first($future);}$total=count($verified);$complete=count(array_filter($verified,fn($p)=>!empty($p['completed'])));$progressTotal=0;$progressMax=0;foreach($verified as$p){$progressTotal+=(int)($p['answered_count']??0);$progressMax+=max(1,(int)($p['journey_total']??($room['journey_length']??27)));}$rid=(string)($room['id']??$room['code']??'');$futureLabels=future_topic_labels();return ['id'=>$rid,'code'=>room_label($rid),'title'=>(string)($room['title']??'Udaan Live'),'journey_length'=>(int)($room['journey_length']??27),'expires_at'=>(string)($room['expires_at']??''),'participants'=>$total,'completed'=>$complete,'completion_pct'=>$total?round($complete/$total*100):0,'avg_progress_pct'=>$progressMax?round($progressTotal/$progressMax*100):0,'ladder'=>$ladder,'future'=>$future,'future_labels'=>$futureLabels,'top_future'=>$topFuture,'commitments'=>count(is_array($room['commitments']??null)?$room['commitments']:[])];}
