<?php
require __DIR__.'/bootstrap.php';$roomId=require_room_id($_GET['room']??'');$room=$store->get($roomId);if(!$room||!is_array($room['challenge_card_ids']??null)){http_response_code(404);exit('Challenge expired or not found.');}$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
 if(!global_csrf_matches($_POST['csrf']??null))$error='Session expired. Refresh and try again.';else{
  $nickname=trim((string)($_POST['nickname']??'Learner'));$deviceInstallId=strtolower(trim((string)($_POST['device_install_id']??'')));$deviceHash=device_identity($deviceInstallId);
  if(strlen($nickname)<2||strlen($nickname)>24)$error='Choose a nickname between 2 and 24 characters.';elseif(!preg_match('/^[\p{L}\p{N} ._\-]{2,24}$/u',$nickname))$error='Use letters, numbers, spaces, dot, dash or underscore.';elseif($deviceHash==='')$error='Secure device identity unavailable. Refresh and try again.';else{
   $identity=daily_device_learning_identity($deviceHash);$bank=cards_by_id();$baseCards=[];foreach($room['challenge_card_ids'] as$id)if(isset($bank[(string)$id]))$baseCards[]=$bank[(string)$id];if(count($baseCards)<3){$error='This challenge no longer has enough available cards.';}else{
    $history=$store->getHistory($identity);$seen=is_array($history['seen_cards']??null)?$history['seen_cards']:[];$pid=rand_id(12);$cacheToken=client_cache_token($identity);$updated=null;$collision=true;$refs=[];$cards=[];$fp='';$fresh=0;$review=0;
    for($allocationAttempt=0;$allocationAttempt<8;$allocationAttempt++){
      $snapshot=$store->get($roomId);if(!$snapshot)break;$used=room_journey_fingerprints($snapshot);$cards=$baseCards;$tries=0;do{$cards=secure_shuffle($cards);$fp=journey_fingerprint_from_cards($cards);$tries++;}while(isset($used[$fp])&&$tries<80);if(isset($used[$fp]))continue;
      $points=allocate_card_points(count($cards));$refs=[];$fresh=0;$review=0;foreach($cards as$i=>$c){$isReview=isset($seen[(string)$c['id']]);$isReview?$review++:$fresh++;$order=isset($c['options'])&&is_array($c['options'])?card_option_order($c):[];$refs[]=['id'=>$c['id'],'position'=>$i+1,'points'=>$points[$i]??0,'review'=>$isReview,'option_order'=>$order];}
      $collision=false;$updated=$store->mutate($roomId,function($r)use($pid,$nickname,$identity,$deviceHash,$refs,$fp,$fresh,$review,$history,$cacheToken,&$collision){$used=room_journey_fingerprints($r);if(isset($used[$fp])){$collision=true;return $r;}$r['participants'][$pid]=['id'=>$pid,'nickname'=>$nickname,'phone_mask'=>'','learning_key'=>$identity,'device_hash'=>$deviceHash,'joined_at'=>now_iso(),'verified_at'=>now_iso(),'last_seen'=>now_iso(),'score'=>10,'stage'=>'journey','completed'=>false,'answers'=>[],'answered_count'=>0,'journey'=>$refs,'journey_fingerprint'=>$fp,'journey_total'=>count($refs),'fresh_count'=>$fresh,'review_count'=>$review,'history_before'=>count(is_array($history['seen_cards']??null)?$history['seen_cards']:[]),'cache_token'=>$cacheToken,'offline_sync_token'=>offline_sync_token($identity,$deviceHash,time()+604800),'challenge_join'=>true];return $r;});
      if($updated&&!$collision)break;
    }
    if(!$updated)$error='Challenge expired. Please ask your friend for a new link.';elseif($collision)$error='Could not allocate a unique challenge order. Please try again.';else{$store->cacheDevice($identity,$deviceHash);$store->markJourneySeen($identity,$cards);$store->cacheJourneySession($identity,$roomId,$refs,[],10);$store->appendSyncEvent(['event_type'=>'friend_challenge_joined','user_hash'=>$identity,'device_hash'=>$deviceHash,'room_id'=>$roomId,'journey_total'=>count($refs),'journey_fingerprint'=>$fp]);participant_set($roomId,$pid);csrf_for($roomId);header('Location: '.route_url('journey',$roomId));exit;}
   }
  }
 }
}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Friend Challenge · Udaan</title><?=common_assets_head()?></head><body><div class="floating-theme"><?=theme_toggle()?></div><main class="challenge-start"><section><a class="brand" href="<?=h(route_url('home'))?>"><span class="brand-mark">उ</span><span>Udaan</span></a><p class="eyebrow">FRIEND CHALLENGE</p><h1>Same ideas.<br>Different order.</h1><p class="lead">A friend challenged you on <?=count($room['challenge_card_ids'])?> learning concepts. Udaan reshuffles both the card order and answer positions so copying is less useful.</p><div class="challenge-rules"><span>Same concepts</span><span>Unique Q&amp;A order</span><span>Shuffled options</span><span>No speed bonus</span></div></section><form class="daily-start-card" method="post" data-progress-submit data-progress-label="Building your challenge"><input type="hidden" name="csrf" value="<?=h(global_csrf())?>"><input type="hidden" name="device_install_id" id="device-install-id" value=""><p class="eyebrow">ACCEPT CHALLENGE</p><h2>Choose a nickname</h2><?php if($error):?><p class="form-error"><?=h($error)?></p><?php endif;?><div class="field"><label>NICKNAME</label><input name="nickname" maxlength="24" required placeholder="e.g. Meera"></div><button class="primary">Start challenge →</button><p class="small-note">Only the nickname appears in this temporary challenge.</p></form></main><script src="<?=h(app_url('assets/js/device-id.js?v=0.9.0'))?>" defer></script><?=common_theme_script()?></body></html>
