<?php
require __DIR__.'/bootstrap.php';

$identity=udaan_player_session_identity();
$player=$identity?$store->getPlayer($identity):null;
if(!$identity||!is_array($player)||empty($player['onboarding_completed'])){header('Location: '.app_url('player'));exit;}

$date=today_key();
$state=udaan_mission_ensure_daily($store,$identity,$player,$date);
$readinessState=$store->getReadinessState($identity);
$readiness=udaan_daily_readiness_for_date($readinessState,$date);
if($readiness)$state=udaan_mission_apply_readiness($store,$identity,$readiness);
$coach=udaan_coach_generate($state,$player,$readinessState,$date);
$recommendations=(array)($coach['recommendations']??[]);
foreach($recommendations as$r)if(is_array($r))udaan_coach_record_shown_once($store,$player,$r);
$summary=(array)($coach['weekly_summary']??[]);
$arenas=udaan_player_arenas();
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Coach · Udaan</title><?=common_assets_head()?><style>
.c-wrap{max-width:1120px;margin:0 auto;padding:24px 20px 72px}.c-head{display:flex;justify-content:space-between;align-items:center;gap:16px}.c-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.hero{display:grid;grid-template-columns:1.25fr .75fr;gap:20px;margin-top:30px}.panel{background:var(--panel,#fff);border:1px solid rgba(90,80,60,.14);border-radius:28px;padding:26px}.hero h1{font-size:clamp(42px,6vw,72px);line-height:.96;margin:6px 0 16px}.summary{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.metric strong{display:block;font-size:38px}.metric small{opacity:.66}.rec-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:16px;margin-top:20px}.rec{display:flex;flex-direction:column;min-height:300px}.rec h2{font-size:27px;margin:8px 0}.rec p{line-height:1.55}.tag{display:inline-flex;align-self:flex-start;border:1px solid rgba(90,80,60,.16);border-radius:999px;padding:7px 10px;font-size:11px;letter-spacing:.06em}.reason{font-family:ui-monospace,monospace;font-size:11px;opacity:.62;margin-top:auto}.evidence{margin:12px 0;padding:12px;border-radius:14px;background:rgba(90,80,60,.05);font-size:12px;line-height:1.45}.accept{margin-top:14px}.empty{opacity:.7}.explain{font-size:13px;line-height:1.55;opacity:.75}@media(max-width:860px){.hero,.rec-grid{grid-template-columns:1fr}.summary{grid-template-columns:repeat(4,1fr)}}@media(max-width:560px){.summary{grid-template-columns:1fr 1fr}.panel{padding:20px}}
</style></head><body><main class="c-wrap"><header class="c-head"><a class="brand" href="<?=h(route_url('home'))?>"><span class="brand-mark">उ</span><span>Udaan Coach</span></a><div class="c-actions"><a class="ghost" href="<?=h(app_url('connect'))?>">Connect</a><a class="ghost" href="<?=h(app_url('today'))?>">Today</a><a class="ghost" href="<?=h(app_url('momentum'))?>">Momentum</a><a class="ghost" href="<?=h(app_url('progress'))?>">Progress</a><?=theme_toggle()?></div></header>

<section class="hero"><div class="panel"><p class="eyebrow">COACH V1 · RULES, NOT BLACK BOX</p><h1>Useful next steps, with reasons you can inspect.</h1><p class="lead">Coach v1 reads your goal, completed/pending Missions, Performance, private readiness band and Momentum. It does not use a generative AI model and does not invent learner facts.</p><p class="explain">Each recommendation shows a stable reason code. Raw readiness answers are not copied into Coach telemetry; only the readiness band may be used for workload guidance.</p></div>
<aside class="panel"><p class="eyebrow">WEEKLY SUMMARY</p><div class="summary"><div class="metric"><strong><?=intval($summary['training_days']??0)?></strong><small>training days · 7d</small></div><div class="metric"><strong><?=intval($summary['missions_completed']??0)?></strong><small>missions completed</small></div><div class="metric"><strong><?=intval($summary['training_minutes']??0)?></strong><small>training minutes</small></div><div class="metric"><strong><?=intval($summary['weekly_goal_progress']??0)?>%</strong><small>weekly goal</small></div></div><p class="explain"><?php if(!empty($summary['top_arena'])):?>Most active Arena: <strong><?=h($arenas[$summary['top_arena']]??ucfirst((string)$summary['top_arena']))?></strong>. <?php endif;?>Readiness check-ins this week: <?=intval($summary['readiness_checkins']??0)?>.</p></aside></section>

<section class="rec-grid"><?php if(!$recommendations):?><article class="panel"><h2>No Coach action needed right now.</h2><p class="empty">Your current plan is already clear. Use Today for Missions and Progress for review.</p></article><?php else:?><?php foreach($recommendations as$r):?><article class="panel rec"><span class="tag"><?=h(strtoupper((string)($r['priority']??'normal')))?> · <?=h(strtoupper((string)($r['type']??'coach')))?></span><h2><?=h((string)$r['title'])?></h2><p><?=h((string)$r['body'])?></p><?php if(!empty($r['evidence'])):?><div class="evidence"><?php foreach((array)$r['evidence'] as$key=>$value):?><div><strong><?=h(str_replace('_',' ',(string)$key))?>:</strong> <?=h(is_scalar($value)?(string)$value:'—')?></div><?php endforeach;?></div><?php endif;?><div class="reason">REASON · <?=h((string)$r['reason_code'])?></div><form class="accept" method="post" action="<?=h(app_url('coach/action'))?>"><input type="hidden" name="csrf" value="<?=h(global_csrf())?>"><input type="hidden" name="recommendation_id" value="<?=h((string)$r['id'])?>"><button class="primary"><?=h((string)$r['action_label'])?> →</button></form></article><?php endforeach;?><?php endif;?></section>

<section class="panel" style="margin-top:20px"><p class="eyebrow">HOW COACH V1 DECIDES</p><p class="explain">Priority order: comeback/recovery → readiness-aware workload → goal-aligned pending Mission → weekly rhythm → milestone prompt. Recommendations are recomputed from current state each time. No recommendation changes a Mission by itself; you remain in control of the action.</p></section>
</main><?=common_theme_script()?></body></html>
