<?php
return [
    'app_name' => 'Udaan Live',
    'version' => '0.11.0',
    'environment' => strtolower((string)(getenv('UDAAN_ENV') ?: 'development')),
    'trust_proxy_headers' => getenv('UDAAN_TRUST_PROXY_HEADERS') !== '0',
    'room_ttl_seconds' => 21600,
    'user_cache_ttl_seconds' => 604800,
    'offline_reserve_cards' => 1008,
    'offline_reserve_ttl_seconds' => 604800,
    'offline_device_bank_cards' => 1008,
    'content_pack_size' => 112,
    'content_trust_epoch' => 2,
    'content_distribution' => 'central-trust-distributed-delivery',
    'default_journey_length' => 27,
    'max_action_cards_per_session' => 1,
    'quiz_option_min' => 3,
    'quiz_option_max' => 5,
    'choice_option_max' => 8,
    'room_unique_journey_order' => true,
    'daily9_enabled' => true,
    'daily9_cards' => 9,
    'friend_challenge_enabled' => true,
    'safe_share_card' => true,
    'anonymous_aggregate_signals' => true,
    'mystery_card_enabled' => true,
    'question_of_india_enabled' => true,
    'card_reflection_seconds' => 3,
    'redis' => [
        'host' => getenv('REDIS_HOST') ?: '127.0.0.1',
        'port' => (int)(getenv('REDIS_PORT') ?: 6379),
        'password' => getenv('REDIS_PASSWORD') ?: '',
        'database' => (int)(getenv('REDIS_DB') ?: 0),
        'enabled' => getenv('REDIS_ENABLED') !== '0',
        'required' => getenv('REDIS_REQUIRED') === '1',
    ],
];
