<?php
require __DIR__.'/bootstrap.php';

$identity=udaan_player_session_identity();
$player=$identity?$store->getPlayer($identity):null;
if(!$identity||!is_array($player)||empty($player['onboarding_completed'])){header('Location: '.app_url('player'));exit;}

$enabled=udaan_social_enabled_for_player($player);
$graph=$store->getSocialGraph();
$friends=$enabled?udaan_social_friends($store,$identity,$graph):[];
$teams=$enabled?udaan_social_teams_for_identity($graph,$identity):[];
$session=&udaan_session();
$flash=is_array($session['social_flash']??null)?$session['social_flash']:null;
unset($session['social_flash']);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Connect · Udaan</title><?=common_assets_head()?><style>
.connect-wrap{max-width:1120px;margin:0 auto;padding:24px 20px 72px}.connect-head{display:flex;justify-content:space-between;align-items:center;gap:16px}.connect-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.hero,.grid{display:grid;grid-template-columns:1.1fr .9fr;gap:20px;margin-top:24px}.panel{background:var(--panel,#fff);border:1px solid rgba(90,80,60,.14);border-radius:28px;padding:26px}.hero h1{font-size:clamp(42px,6vw,70px);line-height:.97;margin:6px 0 16px}.notice{padding:14px 16px;border-radius:16px;background:rgba(70,100,150,.08);margin-top:14px}.warn{background:rgba(160,90,50,.09)}.code{font-family:ui-monospace,monospace;font-size:26px;letter-spacing:.08em;font-weight:700}.row{display:flex;justify-content:space-between;gap:16px;align-items:center;padding:14px 0;border-bottom:1px solid rgba(90,80,60,.11)}.row:last-child{border-bottom:0}.row form{margin:0}.forms{display:grid;grid-template-columns:1fr 1fr;gap:16px}.field{display:flex;flex-direction:column;gap:7px}.small{font-size:13px;line-height:1.5;opacity:.72}.pill{display:inline-flex;border:1px solid rgba(90,80,60,.16);border-radius:999px;padding:6px 9px;font-size:11px}.team-card{display:block;border:1px solid rgba(90,80,60,.13);border-radius:18px;padding:16px;margin-top:10px;text-decoration:none;color:inherit}.team-card strong{font-size:21px}.team-card span{display:block;margin-top:5px;opacity:.66}.empty{opacity:.65}@media(max-width:760px){.hero,.grid,.forms{grid-template-columns:1fr}.panel{padding:20px}}
</style></head><body><main class="connect-wrap"><header class="connect-head"><a class="brand" href="<?=h(route_url('home'))?>"><span class="brand-mark">उ</span><span>Udaan Connect</span></a><div class="connect-actions"><a class="ghost" href="<?=h(app_url('leagues'))?>">Leagues</a><a class="ghost" href="<?=h(app_url('today'))?>">Today</a><a class="ghost" href="<?=h(app_url('coach'))?>">Coach</a><a class="ghost" href="<?=h(app_url('progress'))?>">Progress</a><?=theme_toggle()?></div></header>

<section class="hero"><div class="panel"><p class="eyebrow">FRIENDS + TEAMS · PRIVATE BY DEFAULT</p><h1>Belonging without a public popularity contest.</h1><p class="lead">Connect only through explicit invite codes. There is no public Player search, follower count, open messaging, location sharing or public team directory in v1.</p><?php if(!$enabled):?><div class="notice warn"><strong>Social features are unavailable for under-13 Players in v1.</strong><p class="small">Udaan will not enable friend/team networking for this age group until a verified parent/institution consent model exists.</p></div><?php endif;?><?php if($flash):?><div class="notice"><strong><?=h((string)($flash['message']??'Updated.'))?></strong><?php if(!empty($flash['code'])):?><div class="code"><?=h((string)$flash['code'])?></div><p class="small">Share this code only with the person you intend to invite. The code is not stored in plaintext and will not be shown again.</p><?php endif;?></div><?php endif;?></div>
<aside class="panel"><p class="eyebrow">V1 SAFETY LIMITS</p><p><span class="pill">50 friends max</span> <span class="pill">5 teams max</span> <span class="pill">8 members/team</span></p><p class="small">Friend invites are one-time and expire in 24 hours. Team invites are one-time and expire in 7 days. Team challenges measure participation—not speed, rank or “best member”.</p></aside></section>

<?php if($enabled):?><section class="grid"><div class="panel"><p class="eyebrow">INVITES</p><h2>Connect by code</h2><div class="forms"><form method="post" action="<?=h(app_url('connect/action'))?>"><input type="hidden" name="csrf" value="<?=h(global_csrf())?>"><input type="hidden" name="action" value="create_friend_invite"><div class="field"><label>FRIEND INVITE</label><p class="small">Generate a one-time 24-hour invite.</p><button class="primary">Create friend invite →</button></div></form><form method="post" action="<?=h(app_url('connect/action'))?>"><input type="hidden" name="csrf" value="<?=h(global_csrf())?>"><input type="hidden" name="action" value="accept_friend_invite"><div class="field"><label>USE FRIEND CODE</label><input name="code" maxlength="20" autocomplete="off" placeholder="16-character code" required><button class="primary">Connect →</button></div></form></div><hr style="border:0;border-top:1px solid rgba(90,80,60,.11);margin:24px 0"><div class="forms"><form method="post" action="<?=h(app_url('connect/action'))?>"><input type="hidden" name="csrf" value="<?=h(global_csrf())?>"><input type="hidden" name="action" value="create_team"><div class="field"><label>CREATE SMALL TEAM</label><input name="team_name" maxlength="32" placeholder="e.g. Biology Crew" required><button class="primary">Create team →</button></div></form><form method="post" action="<?=h(app_url('connect/action'))?>"><input type="hidden" name="csrf" value="<?=h(global_csrf())?>"><input type="hidden" name="action" value="accept_team_invite"><div class="field"><label>JOIN TEAM BY CODE</label><input name="code" maxlength="20" autocomplete="off" placeholder="16-character code" required><button class="primary">Join team →</button></div></form></div></div>

<div class="panel"><p class="eyebrow">FRIENDS</p><h2>Your private connections</h2><?php if(!$friends):?><p class="empty">No friend connections yet.</p><?php else:?><?php foreach($friends as$f):?><div class="row"><div><strong><?=h((string)$f['nickname'])?></strong><br><small>Connected <?=h(substr((string)$f['since'],0,10))?></small></div><form method="post" action="<?=h(app_url('connect/action'))?>"><input type="hidden" name="csrf" value="<?=h(global_csrf())?>"><input type="hidden" name="action" value="remove_friend"><input type="hidden" name="relationship_id" value="<?=h((string)$f['relationship_id'])?>"><button class="ghost">Remove</button></form></div><?php endforeach;?><?php endif;?></div></section>

<section class="panel" style="margin-top:20px"><p class="eyebrow">TEAMS</p><h2>Small groups you explicitly joined</h2><?php if(!$teams):?><p class="empty">No teams yet.</p><?php else:?><?php foreach($teams as$t):?><a class="team-card" href="<?=h(app_url('team/'.rawurlencode((string)$t['id'])))?>"><strong><?=h((string)$t['name'])?></strong><span><?=count((array)$t['members'])?> members · <?=h((string)($t['members'][$identity]['role']??'member'))?></span></a><?php endforeach;?><?php endif;?></section><?php endif;?>
</main><?=common_theme_script()?></body></html>