<?php
require __DIR__.'/bootstrap.php';

$loginError='';$actionError='';$verification=null;$verificationToken='';$importSuccess=null;$migrationSuccess=null;$pasted='';

if($_SERVER['REQUEST_METHOD']==='POST' && isset($_POST['admin_login'])){
    $key=(string)($_POST['admin_key']??'');
    if(content_admin_login($key)){header('Location: '.app_url('admin/content-bank'));exit;}
    $loginError='Access key not accepted.';usleep(350000);
}

if(!content_admin_authenticated()){
    // Initializes a strong local key on first visit. It remains web-inaccessible under data/.htaccess.
    content_admin_key();
    ?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Content Bank Access · Udaan</title><?=common_assets_head()?></head><body><div class="shell"><header class="site-head"><a class="brand" href="<?=h(route_url('home'))?>"><span class="brand-mark">उ</span><span>Udaan</span></a><div class="head-actions"><span class="ghost">Content Bank · Protected</span><?=theme_toggle()?></div></header><main class="admin-login-wrap"><section class="admin-login-card"><p class="eyebrow">CONTENT ADMIN</p><h1>Verify before anything enters the bank.</h1><p class="admin-lead">Enter the Content Admin access key. On first use the app creates a strong key at <code>data/content-admin.key</code>. Read it through Cloudways SFTP/SSH; the file is blocked from public web access.</p><?php if($loginError):?><p class="form-error"><?=h($loginError)?></p><?php endif;?><form method="post" data-progress-submit data-progress-label="Unlocking Content Bank"><input type="hidden" name="admin_login" value="1"><div class="field"><label>CONTENT ADMIN ACCESS KEY</label><input name="admin_key" type="password" autocomplete="current-password" required autofocus></div><button class="primary">Unlock Content Bank →</button></form><p class="small-note">You can override the file key with the server environment variable <code>UDAAN_CONTENT_ADMIN_KEY</code>.</p></section></main></div><?=common_theme_script()?></body></html><?php exit;
}

if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!content_admin_csrf_matches($_POST['csrf']??null))$actionError='Security token expired. Refresh the page and try again.';
    elseif(isset($_POST['logout'])){content_admin_logout();header('Location: '.app_url('admin/content-bank'));exit;}
    elseif(isset($_POST['verify_json'])){
        $pasted=(string)($_POST['cards_json']??'');
        try{$verification=verify_content_json($pasted);$verificationToken=save_verification($verification);}catch(Throwable $e){$actionError=$e->getMessage();}
    }elseif(isset($_POST['import_verified'])){
        try{$importSuccess=import_verified_batch((string)($_POST['verification_token']??''));}catch(Throwable $e){$actionError=$e->getMessage();}
    }elseif(isset($_POST['migrate_v060'])){
        try{$migrationSuccess=content_v060_migrate_future_choices();}catch(Throwable $e){$actionError=$e->getMessage();}
    }
}
$stats=bank_stats();$history=content_import_history();$csrf=content_admin_csrf();$migrationStatus=content_v060_migration_status();
$readyCount=is_array($verification)?count($verification['ready']??[]):0;$reviewCount=is_array($verification)?count($verification['review']??[]):0;$rejectedCount=is_array($verification)?count($verification['rejected']??[]):0;
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Content Bank · Udaan</title><?=common_assets_head()?></head><body><div class="shell content-admin-shell"><header class="site-head"><a class="brand" href="<?=h(route_url('home'))?>"><span class="brand-mark">उ</span><span>Udaan</span></a><div class="head-actions"><a class="ghost" href="<?=h(route_url('home'))?>">Presentation</a><form method="post" class="inline-form"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><button class="ghost ghost-button" name="logout" value="1">Lock</button></form><?=theme_toggle()?></div></header>
<main class="content-admin">
<section class="admin-hero"><div><p class="eyebrow">CONTENT BANK</p><h1>Paste. Verify. Then import.</h1><p class="lead">Nothing is written to the live learning bank until server-side verification completes. Invalid cards, duplicate GUIDs and likely semantic duplicates are excluded before import.</p></div><div class="bank-total"><span>LIVE BANK</span><strong><?=intval($stats['count'])?></strong><small><?=intval($stats['pillars'])?> pillars · <?=h((string)$stats['version'])?></small></div></section>

<?php if($actionError):?><div class="admin-alert error"><strong>Verification/import stopped.</strong><span><?=h($actionError)?></span></div><?php endif;?>
<?php if($importSuccess):?><div class="admin-alert success"><strong>Import complete.</strong><span><?=intval($importSuccess['imported'])?> verified cards added. Bank <?=intval($importSuccess['bank_before'])?> → <?=intval($importSuccess['bank_after'])?>. Backup: <?=h((string)$importSuccess['backup'])?>.</span></div><?php endif;?>
<?php if($migrationSuccess):?><div class="admin-alert success"><strong>v0.6 Future-choice migration complete.</strong><span><?=intval($migrationSuccess['changed']??0)?> legacy cards upgraded. Backup: <?=h((string)($migrationSuccess['backup']??'not required'))?>.</span></div><?php endif;?>
<?php if(!empty($migrationStatus['needed'])):?><section class="admin-panel"><div class="panel-head"><div><p class="eyebrow">V0.6 CONTENT MIGRATION</p><h2>Upgrade legacy Future choices safely.</h2></div><span class="status-pill warning"><?=intval($migrationStatus['legacy_future_choice_cards'])?> cards</span></div><p class="admin-lead">Your existing live bank contains the older three-option Future-interest cards. This migration preserves every imported card/GUID, changes only those legacy Future cards to the approved five-option format, creates a full backup, and rebuilds signed packs.</p><form method="post" data-progress-submit data-progress-label="Migrating Future choice cards" onsubmit="return confirm('Back up and upgrade the legacy Future choice cards now?')"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><button class="primary" name="migrate_v060" value="1">Back up &amp; migrate <?=intval($migrationStatus['legacy_future_choice_cards'])?> cards →</button></form></section><?php endif;?>

<div class="admin-grid"><section class="admin-panel paste-panel"><div class="panel-head"><div><p class="eyebrow">STEP 1</p><h2>Paste JSON</h2></div><span class="status-pill neutral">No direct import</span></div><form method="post" data-progress-submit data-progress-label="Verifying card batch"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><div class="field"><label>UDAAN CARD JSON · ARRAY OR { "cards": [...] }</label><textarea class="json-paste" name="cards_json" spellcheck="false" placeholder='[
  {
    "id": "550e8400-e29b-41d4-a716-446655440000",
    "pillar": "science",
    "kind": "quiz",
    ...
  }
]' required><?=h($pasted)?></textarea></div><div class="verify-explainer"><span>Verification checks</span><div><b>JSON syntax</b><b>Schema</b><b>UUID/GUID</b><b>9 pillars</b><b>4 card types</b><b>Grade range</b><b>Answer integrity</b><b>Duplicate GUID</b><b>Likely duplicate concept</b></div></div><button class="primary" name="verify_json" value="1">Verify JSON →</button><p class="small-note">Maximum 1,500 cards / 5 MB per batch. Verification does not modify <code>cards.json</code>.</p></form></section>

<section class="admin-panel verify-panel"><div class="panel-head"><div><p class="eyebrow">STEP 2</p><h2>Verification result</h2></div><?php if($verification):?><span class="status-pill <?=($rejectedCount||$reviewCount)?'warning':'good'?>">Verified <?=h(date('H:i:s'))?></span><?php else:?><span class="status-pill neutral">Waiting</span><?php endif;?></div>
<?php if(!$verification):?><div class="empty-state"><span>✓</span><h3>Import remains locked.</h3><p>Paste a batch and press Verify. The Import button appears only after the server creates a verified snapshot.</p></div><?php else:?><div class="verify-metrics"><div><strong><?=intval($verification['submitted'])?></strong><span>SUBMITTED</span></div><div class="metric-good"><strong><?=$readyCount?></strong><span>READY</span></div><div class="metric-warn"><strong><?=$reviewCount?></strong><span>REVIEW / EXCLUDED</span></div><div class="metric-bad"><strong><?=$rejectedCount?></strong><span>REJECTED</span></div></div><div class="verified-lock"><strong>Verified snapshot locked</strong><span>The final import uses verification token <code><?=h(substr($verificationToken,0,8))?>…</code>, not the textarea. Expires in 30 minutes.</span></div><?php if($readyCount):?><form method="post" class="import-action" data-progress-submit data-progress-label="Importing verified cards safely"><input type="hidden" name="csrf" value="<?=h($csrf)?>"><input type="hidden" name="verification_token" value="<?=h($verificationToken)?>"><button class="primary import-primary" name="import_verified" value="1">Import <?=$readyCount?> Verified Card<?=$readyCount===1?'':'s'?> →</button><p class="small-note">An automatic full-bank backup is created before the atomic write. Review/rejected cards are not imported.</p></form><?php else:?><div class="admin-alert error compact"><strong>Nothing can be imported.</strong><span>Correct the JSON and verify again.</span></div><?php endif;?><?php endif;?></section></div>

<?php if($verification):?><section class="admin-panel verification-detail"><div class="panel-head"><div><p class="eyebrow">VERIFICATION DETAIL</p><h2>What will enter the bank?</h2></div><span class="ghost">Bank before: <?=intval($verification['bank_before'])?></span></div><div class="distribution-grid"><div><h3>Ready by pillar</h3><?php foreach(import_pillars() as $key=>$name):$n=(int)($verification['pillar_counts'][$key]??0);?><div class="dist-row"><span><?=h($name)?></span><b><?=$n?></b></div><?php endforeach;?></div><div><h3>Ready by interaction</h3><?php foreach(import_kinds() as $kind):?><div class="dist-row"><span><?=h(ucfirst($kind))?></span><b><?=intval($verification['kind_counts'][$kind]??0)?></b></div><?php endforeach;?></div></div>
<?php if($reviewCount):?><div class="issue-block"><h3>Needs review — excluded from import</h3><p>These cards are structurally valid but look too similar to an existing concept. Edit/rephrase only when they add materially different educational value, then verify again.</p><div class="issue-list"><?php foreach(array_slice($verification['review'],0,100) as $row):?><div><span>#<?=intval($row['index'])?> · <?=h($row['title']?:$row['id'])?></span><small><?=h($row['reason'])?></small></div><?php endforeach;?></div></div><?php endif;?>
<?php if($rejectedCount):?><div class="issue-block rejected"><h3>Rejected — cannot be imported</h3><div class="issue-list"><?php foreach(array_slice($verification['rejected'],0,100) as $row):?><div><span>#<?=intval($row['index'])?> · <?=h($row['title']?:($row['id']?:'Unnamed card'))?></span><small><?=h($row['reason'])?></small></div><?php endforeach;?></div></div><?php endif;?></section><?php endif;?>

<section class="admin-panel"><div class="panel-head"><div><p class="eyebrow">LIVE BANK</p><h2>Pillar distribution</h2></div><span class="status-pill good"><?=intval($stats['count'])?> active/available cards</span></div><div class="pillar-stat-grid"><?php foreach(import_pillars() as $key=>$name):?><div><span><?=h($name)?></span><strong><?=intval($stats['by_pillar'][$key]??0)?></strong></div><?php endforeach;?></div></section>

<section class="admin-panel"><div class="panel-head"><div><p class="eyebrow">AUDIT</p><h2>Recent imports</h2></div><span class="small-note">Last 100 imports retained</span></div><?php if(!$history):?><div class="empty-history">No JSON batches have been imported through this screen yet.</div><?php else:?><div class="history-list"><?php foreach(array_slice($history,0,12) as $row):?><div class="history-row"><div><strong><?=h(date('d M Y · H:i',strtotime((string)($row['time']??'now'))))?></strong><small><?=h((string)($row['backup']??''))?></small></div><span><?=intval($row['imported']??0)?> imported</span><span><?=intval($row['review_excluded']??0)?> review</span><span><?=intval($row['rejected']??0)?> rejected</span><b><?=intval($row['bank_before']??0)?> → <?=intval($row['bank_after']??0)?></b></div><?php endforeach;?></div><?php endif;?></section>
</main></div><?=common_theme_script()?></body></html>
