<?php
require __DIR__.'/bootstrap.php';
$error='';$today=today_key();$s=&udaan_session();$existing=is_array($s['daily9']??null)?($s['daily9'][$today]??null):null;
if(is_string($existing)&&$existing!==''&&$store->get($existing)){header('Location: '.route_url('journey',$existing));exit;}
if($_SERVER['REQUEST_METHOD']==='POST'){
    if(!global_csrf_matches($_POST['csrf']??null))$error='Session expired. Refresh and try again.';
    else{
        $nickname=trim((string)($_POST['nickname']??'Learner'));$deviceInstallId=strtolower(trim((string)($_POST['device_install_id']??'')));$deviceHash=device_identity($deviceInstallId);
        if(strlen($nickname)<2||strlen($nickname)>24)$error='Choose a nickname between 2 and 24 characters.';
        elseif(!preg_match('/^[\p{L}\p{N} ._\-]{2,24}$/u',$nickname))$error='Use letters, numbers, spaces, dot, dash or underscore.';
        elseif($deviceHash==='')$error='This browser could not create a secure device installation ID. Refresh and try again.';
        else{
            $identity=daily_device_learning_identity($deviceHash);$built=build_unseen_journey($identity,9,$store,[],[]);$cards=$built['cards'];$refs=array_map(fn($c)=>['id'=>$c['id'],'position'=>$c['position'],'points'=>$c['points'],'review'=>$c['review'],'option_order'=>array_values($c['option_order']??[])],$cards);
            $id=room_id();$pid=rand_id(12);$cacheToken=client_cache_token($identity);$expires=time()+(int)($config['room_ttl_seconds']??21600);
            $room=['id'=>$id,'code'=>$id,'title'=>'Today\'s Daily 9','mode'=>'daily9','journey_length'=>9,'created_at'=>now_iso(),'expires_at'=>date(DATE_ATOM,$expires),'participants'=>[],'signals'=>['future_topics'=>[]],'commitments'=>[],'challenge_card_ids'=>array_values(array_map(fn($c)=>(string)$c['id'],$cards)),'daily_key'=>$today];
            $room['participants'][$pid]=['id'=>$pid,'nickname'=>$nickname,'phone_mask'=>'','learning_key'=>$identity,'device_hash'=>$deviceHash,'joined_at'=>now_iso(),'verified_at'=>now_iso(),'last_seen'=>now_iso(),'score'=>10,'stage'=>'journey','completed'=>false,'answers'=>[],'answered_count'=>0,'journey'=>$refs,'journey_fingerprint'=>(string)$built['journey_fingerprint'],'journey_total'=>9,'fresh_count'=>(int)$built['fresh_count'],'review_count'=>(int)$built['review_count'],'history_before'=>(int)$built['history_before'],'cache_token'=>$cacheToken,'offline_sync_token'=>offline_sync_token($identity,$deviceHash,time()+604800)];
            $store->put($id,$room);$store->cacheDevice($identity,$deviceHash);$store->markJourneySeen($identity,$cards);$store->cacheJourneySession($identity,$id,$refs,[],10);$store->appendSyncEvent(['event_type'=>'daily9_started','user_hash'=>$identity,'device_hash'=>$deviceHash,'room_id'=>$id,'daily_key'=>$today,'journey_total'=>9,'journey_card_ids'=>$room['challenge_card_ids'],'journey_fingerprint'=>$built['journey_fingerprint']]);participant_set($id,$pid);csrf_for($id);if(!isset($s['daily9'])||!is_array($s['daily9']))$s['daily9']=[];$s['daily9'][$today]=$id;header('Location: '.route_url('journey',$id));exit;
        }
    }
}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Daily 9 · Udaan</title><?=common_assets_head()?></head><body><div class="floating-theme"><?=theme_toggle()?></div><main class="daily-start"><section class="daily-start-copy"><a class="brand" href="<?=h(route_url('home'))?>"><span class="brand-mark">उ</span><span>Udaan</span></a><p class="eyebrow">TODAY'S DAILY 9</p><h1>Nine ideas.<br>About two minutes.</h1><p class="lead">One balanced card from each Udaan pillar. Unseen learning first. Your options and order are randomized and then frozen for offline resume.</p><div class="daily-pillar-list"><span>Think</span><span>Science</span><span>Roots</span><span>Maths</span><span>Build</span><span>Future</span><span>Values</span><span>India & World</span><span>Life</span></div></section><form class="daily-start-card" method="post" data-progress-submit data-progress-label="Preparing your Daily 9"><input type="hidden" name="csrf" value="<?=h(global_csrf())?>"><input type="hidden" name="device_install_id" id="device-install-id" value=""><p class="eyebrow">START IN SECONDS</p><h2>What should Udaan call you?</h2><?php if($error):?><p class="form-error"><?=h($error)?></p><?php endif;?><div class="field"><label>NICKNAME</label><input name="nickname" maxlength="24" required autocomplete="nickname" placeholder="e.g. Aarav"></div><div class="privacy"><strong>No account required for Daily 9</strong><span>This device receives a random installation GUID. The server stores only its one-way HMAC identity for no-repeat history and sync.</span></div><button class="primary">Start today's Daily 9 →</button><p class="small-note">Available offline after the encrypted device bank is prepared.</p></form></main><script src="<?=h(app_url('assets/js/device-id.js?v=0.12.0'))?>" defer></script><?=common_theme_script()?></body></html>
