<?php
require __DIR__.'/bootstrap.php';$roomId=require_room_id($_GET['room']??'');canonicalize_get_route('complete',$roomId);$pid=participant_id_for($roomId);$room=$store->get($roomId);if(!$room||!$pid||!isset($room['participants'][$pid])){header('Location: '.route_url('join',$roomId));exit;}$p=$room['participants'][$pid];$answered=(int)($p['answered_count']??0);$total=(int)($p['journey_total']??0);if($total<1||$answered<$total){header('Location: '.route_url('journey',$roomId));exit;}$justCompleted=false;
if(empty($p['completed'])){$room=$store->mutate($roomId,function($r)use($pid,&$justCompleted){if(isset($r['participants'][$pid])&&empty($r['participants'][$pid]['completed'])){$r['participants'][$pid]['completed']=true;$r['participants'][$pid]['stage']='complete';$r['participants'][$pid]['completed_at']=now_iso();$justCompleted=true;}return $r;})??$room;}$p=$room['participants'][$pid];if(!empty($p['learning_key'])){$store->cacheComplete((string)$p['learning_key'],$roomId,(int)($p['score']??0),(int)($p['answered_count']??0));if($justCompleted)$store->appendSyncEvent(['event_type'=>($room['mode']??'live')==='daily9'?'daily9_completed':'journey_completed','user_hash'=>(string)$p['learning_key'],'device_hash'=>(string)($p['device_hash']??''),'room_id'=>$roomId,'score'=>(int)($p['score']??0),'answered_count'=>(int)($p['answered_count']??0),'journey_total'=>$total]);}
$state=room_public_state($room);$rank='—';foreach($state['ladder']as$x)if($x['nickname']===$p['nickname']&&$x['score']===$p['score']){$rank='#'.$x['rank'];break;}$badges=completion_badges($p,$room);$isDaily=($room['mode']??'')==='daily9';
if($isDaily&&$justCompleted){
    $playerIdentity=udaan_player_session_identity();$player=$playerIdentity?$store->getPlayer($playerIdentity):null;
    if($playerIdentity&&is_array($player)&&!empty($player['onboarding_completed'])){
        $missionDate=(string)($room['daily_key']??today_key());
        udaan_mission_ensure_daily($store,$playerIdentity,$player,$missionDate);
        udaan_mission_complete_by_source($store,$playerIdentity,$player,'daily:'.$missionDate.':daily9',[
            'room_id'=>$roomId,'answered_count'=>(int)($p['answered_count']??0),'score'=>(int)($p['score']??0),
        ]);
    }
}
$challengeUrl=!empty($room['challenge_card_ids'])?absolute_app_url('challenge/'.$roomId):'';$mysteryUrl=app_url('mystery/'.$roomId);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Complete · Udaan</title><?=common_assets_head()?></head><body><div class="floating-theme"><?=theme_toggle()?></div><main class="done-screen"><div class="done-card"><p class="eyebrow"><?=$isDaily?'DAILY 9 COMPLETE':'JOURNEY COMPLETE'?></p><h1>Well done, <?=h((string)$p['nickname'])?>.</h1><p class="serif done-lede"><?=$isDaily?'Nine pillars explored in one short daily ritual.':'You completed '.intval($total).' balanced micro-learning cards across nine pillars.'?> <?=intval($p['fresh_count']??0)?> were new to you.</p><div class="score"><div><strong><?=intval($p['score'])?></strong><small>POINTS</small></div></div><p><strong><?=h($rank)?></strong> on this temporary ladder · <?=intval($state['participants'])?> participant<?=intval($state['participants'])===1?'':'s'?></p><div class="completion-stats"><span><?=intval($p['fresh_count']??0)?> new cards</span><span><?=intval($p['history_before']??0)+intval($p['fresh_count']??0)?> total card GUIDs seen</span></div><div class="badge-strip"><?php foreach($badges as$b):?><span><i><?=h((string)$b['icon'])?></i><?=h((string)$b['name'])?></span><?php endforeach;?></div>
<?php if($isDaily&&$challengeUrl):?><section class="share-achievement"><div class="share-card-visual"><p>UDAAN · DAILY 9</p><h2><?=h((string)$p['nickname'])?> completed today's Daily 9.</h2><div><strong>9 / 9</strong><span>ideas explored</span></div><small>Knowledge · Curiosity · Character · Future</small></div><div class="share-challenge"><div class="qr-canvas small-qr" data-qr-value="<?=h($challengeUrl)?>"><div class="qr-loading">QR</div></div><div><p class="eyebrow">CHALLENGE FRIENDS</p><h3>Same concepts. Different order.</h3><p>Their card order and answer positions are independently shuffled.</p><button class="primary compact" data-safe-share data-share-url="<?=h($challengeUrl)?>" data-share-name="<?=h((string)$p['nickname'])?>">Share challenge →</button></div></div></section><?php endif;?>
<div class="done-actions"><?php if($isDaily):?><a href="<?=h($mysteryUrl)?>">Open Mystery Card ✦</a><a href="<?=h(app_url('question-of-india'))?>">Question of India</a><?php endif;?><a href="<?=h(route_url('journey',$roomId))?>">Review this journey</a><a href="<?=h(app_url('offline-learning.php'))?>">Open offline learning</a><?php if(!$isDaily):?><a href="<?=h(route_url('join',$roomId))?>">Reopen this room</a><?php endif;?></div><p class="small-note" style="margin-top:28px">This device keeps an encrypted signed learning bank of up to 1,008 approved cards. Future sessions continue to prioritize unseen GUIDs.</p></div></main><?php if($isDaily&&$challengeUrl):?><script src="<?=h(app_url('assets/js/qr-local.js?v=0.8.0'))?>" defer></script><script src="<?=h(app_url('assets/js/share-card.js?v=0.8.0'))?>" defer></script><?php endif;?><?=common_theme_script()?></body></html>
