<?php
require __DIR__.'/bootstrap.php';$error='';
if($_SERVER['REQUEST_METHOD']==='POST'){
  if(!global_csrf_matches($_POST['csrf']??null))$error='Session expired. Refresh and try again.';
  else{$length=normalize_journey_length($_POST['journey_length']??27);$room=new_room(trim((string)($_POST['title']??''))?:'Future India · Live Learning',$length);$store->put($room['id'],$room);host_set($room['id']);header('Location: '.route_url('present',$room['id']));exit;}
}
$stats=bank_stats();$qoi=question_of_india_card();
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Udaan · Daily Learning</title><?=common_assets_head()?></head><body><div class="shell"><header class="site-head"><a class="brand" href="<?=h(route_url('home'))?>"><span class="brand-mark">उ</span><span>Udaan</span></a><div class="head-actions"><button class="ghost" type="button" data-pwa-install hidden>Install app</button><a class="ghost" href="<?=h(app_url('admin/content-bank'))?>">Content Bank</a><span class="ghost">v0.6.0 · <?=h($store->backend())?></span><?=theme_toggle()?></div></header>
<main class="growth-home"><section class="growth-hero"><div><p class="eyebrow">CENTRALIZE TRUST · DECENTRALIZE DISTRIBUTION</p><h1>A daily student ritual<br>that happens to make you smarter.</h1><p class="lead">Fast, verified micro-learning across nine pillars. Built to work on weak networks, continue offline, and keep every learner's journey different.</p><div class="principles"><span><?=intval($stats['count'])?> approved seed cards</span><span>1,008 offline/device</span><span>9 pillars</span><span>Signed Ed25519 packs</span><span>No-repeat GUID history</span></div></div><a class="daily9-hero-card" href="<?=h(app_url('daily'))?>"><div><p class="eyebrow">TODAY'S DAILY 9</p><h2>9 new ideas.</h2><p>One from every pillar · about 2 minutes.</p></div><div class="daily9-progress"><strong>9</strong><span>CARDS</span></div><b>START →</b></a></section>
<section class="growth-grid"><a class="growth-card qoi-home" href="<?=h(app_url('question-of-india'))?>"><p class="eyebrow">QUESTION OF INDIA</p><h2><?=h((string)$qoi['title'])?></h2><p>Answer once, then see only anonymous aggregate percentages.</p><span>Answer today's question →</span></a><article class="growth-card mystery-home"><p class="eyebrow">WHY COME BACK?</p><h2>Daily novelty without an endless feed.</h2><p>Daily 9 completion can unlock a Mystery Card, a friend challenge and lightweight learning badges.</p><span>Useful minutes, not screen-time minutes.</span></article><article class="growth-card offline-home"><p class="eyebrow">OFFLINE LEARNING BANK</p><h2>Up to 1,008 verified cards on this device.</h2><p>Encrypted IndexedDB + signed content packs. Answers queue locally and sync when connectivity returns.</p><span>9 pillars · up to 112 each</span></article></section>
<section class="live-section"><div class="live-copy"><p class="eyebrow">TEACHER / ASSEMBLY / PRESENTATION</p><h2>Run a 2–3 minute live challenge.</h2><p>One QR can bring a whole room into a 21–36-card experience. Every participant receives a different ordered sequence and shuffled options. The ladder rewards completion, not speed.</p><div class="live-benefits"><span>Screen OTP</span><span>Live ladder</span><span>Anonymous response signals</span><span>≤1 action card</span><span>Q&A-first composition</span></div></div><form class="create-card" method="post" data-progress-submit data-progress-label="Creating live room"><input type="hidden" name="csrf" value="<?=h(global_csrf())?>"><p class="eyebrow">PRESENTER</p><h2>Create a live room</h2><?php if($error):?><p class="form-error"><?=h($error)?></p><?php endif;?><div class="field"><label>ROOM TITLE</label><input name="title" value="Future India · Live Learning" maxlength="80" required></div><div class="field"><label>CARDS PER PARTICIPANT</label><select name="journey_length"><?php foreach(journey_length_options() as $n):?><option value="<?=$n?>" <?=$n===27?'selected':''?>><?=$n?> cards<?=$n===27?' · recommended 2–3 min':''?></option><?php endforeach;?></select></div><button class="primary">Create room & show QR →</button><p class="small-note">Temporary room responses expire automatically. Pseudonymous seen-card history remains so future visits stay fresh.</p></form></section>
<footer class="growth-footer"><strong>Udaan</strong><span>Knowledge · Curiosity · Character · Future</span><span>Prototype v0.6.0</span></footer></main></div><?=common_theme_script()?></body></html>
