<?php
require __DIR__.'/bootstrap.php';
$roomId=require_room_id($_GET['room']??'');canonicalize_get_route('journey',$roomId);$room=$store->get($roomId);$pid=participant_id_for($roomId);
if(!$room||!$pid||empty($room['participants'][$pid]['verified_at'])){header('Location: '.route_url('join',$roomId));exit;}
$p=$room['participants'][$pid];$cards=journey_for_participant($p);if(!$cards){header('Location: '.route_url('join',$roomId));exit;}
$csrf=csrf_for($roomId);$answered=is_array($p['answers']??null)?$p['answers']:[];$total=count($cards);$cacheToken=(string)($p['cache_token']??client_cache_token((string)($p['learning_key']??'')));
$publicCards=[];foreach($cards as$c){$pc=public_card_payload($c,true);$pc['position']=$c['position'];$pc['points']=$c['points'];$pc['review']=$c['review'];$publicCards[]=$pc;}
$seed=['version'=>2,'room'=>$roomId,'cache_token'=>$cacheToken,'expires_at'=>$room['expires_at']??null,'generated_at'=>now_iso(),'cards'=>$publicCards,'server_answers'=>$answered,'answered_count'=>(int)($p['answered_count']??0),'total'=>$total,'answer_url'=>route_url('answer',$roomId),'complete_url'=>route_url('complete',$roomId),'offline_pack_url'=>route_url('offline_pack',$roomId),'offline_sync_url'=>route_url('offline_sync',$roomId),'offline_sync_token'=>(string)($p['offline_sync_token']??''),'offline_reserve_capacity'=>(int)($config['offline_reserve_cards']??1008),'offline_url'=>app_url('offline-learning.php'),'content_manifest_url'=>app_url('content/manifest'),'offline_device_bank_cards'=>(int)($config['offline_device_bank_cards']??1008)];
$seedJson=json_encode($seed,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT);if(!is_string($seedJson))$seedJson='{}';
?><!doctype html><html data-room="<?=h($roomId)?>" data-csrf="<?=h($csrf)?>" data-answer-url="<?=h(route_url('answer',$roomId))?>" data-complete-url="<?=h(route_url('complete',$roomId))?>" data-reflection-ms="<?=intval(($config['card_reflection_seconds']??3)*1000)?>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>Your <?=intval($total)?>-card journey · Udaan</title><?=common_assets_head('#141510')?></head><body class="journey-page"><div class="floating-theme journey-theme"><?=theme_toggle()?></div><div class="offline-badge">Offline · answers are being kept on this device</div><main class="journey">
<?php foreach($cards as$i=>$c):$isAnswered=isset($answered[$c['id']]);$pct=round((($i+1)/$total)*100);?><section class="story <?=h(pillar_class((string)$c['pillar']))?>" data-card="<?=h((string)$c['id'])?>" data-kind="<?=h((string)$c['kind'])?>" data-index="<?=$i?>" <?=$isAnswered?'data-locked="1"':''?>><div class="story-inner"><div class="story-top"><div class="story-progress-long"><i style="width:<?=$pct?>%"></i></div><span class="story-index"><?=($i+1)?> / <?=$total?></span></div><div class="story-body"><div class="story-meta"><p class="eyebrow"><?=h((string)$c['label'])?></p><span><?=!empty($c['review'])?'SMART REVIEW':'NEW TO YOU'?> · +<?=intval($c['points'])?></span></div><h1><?=h((string)$c['title'])?></h1><p class="story-sub"><?=h((string)$c['subtitle'])?></p>
<?php if(in_array($c['kind'],['choice','quiz','action'],true)):?><div class="choice-grid <?=count($c['options']??[])>4?'many':''?>"><?php foreach($c['options'] as$o):?><button class="choice" data-choice="<?=h((string)$o['id'])?>" <?=$isAnswered?'disabled':''?>><?=h((string)$o['label'])?></button><?php endforeach;?></div><div class="feedback" data-feedback><?=($isAnswered&&$c['kind']==='quiz')?h((string)($c['explain']??'')):''?></div>
<?php elseif($c['kind']==='reveal'):?><div class="reveal-box <?=$isAnswered?'open':''?>" data-reveal><strong>Tap to reveal</strong><div class="reveal-answer"><?=h((string)$c['reveal'])?></div></div><div class="feedback" data-feedback></div><?php endif;?></div><div class="story-footer"><span><?=h((string)$p['nickname'])?> · <?=h(pillar_label((string)$c['pillar']))?></span><span class="swipe-hint">Answer to continue ↑</span></div></div></section><?php endforeach;?>
</main><div class="status-toast">Saved</div><script src="<?=h(app_url('assets/js/vault.js?v=0.6.0'))?>"></script><script src="<?=h(app_url('assets/js/content-packs.js?v=0.6.0'))?>"></script><script type="application/json" id="udaan-journey-seed"><?=$seedJson?></script><?=common_theme_script()?><script src="<?=h(app_url('assets/js/journey.js?v=0.6.0'))?>" defer></script></body></html>
