<?php
require __DIR__.'/bootstrap.php';

$identity=udaan_player_session_identity();$player=$identity?$store->getPlayer($identity):null;
if(!$identity||!is_array($player)||empty($player['onboarding_completed'])){header('Location: '.app_url('player'));exit;}

$enabled=udaan_social_enabled_for_player($player);
$social=$store->getSocialGraph();$competition=$store->getCompetitionState();
$leagues=$enabled?udaan_competition_leagues_for_identity($store,$identity,$competition):[];
$teams=$enabled?udaan_social_teams_for_identity($social,$identity):[];
$ownedTeams=array_values(array_filter($teams,fn($t)=>(($t['members'][$identity]['role']??'member')==='owner')));
$session=&udaan_session();$flash=is_array($session['competition_flash']??null)?$session['competition_flash']:null;unset($session['competition_flash']);
$arenas=udaan_player_arenas();
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Leagues · Udaan</title><?=common_assets_head()?><style>
.l-wrap{max-width:1120px;margin:0 auto;padding:24px 20px 72px}.l-head{display:flex;justify-content:space-between;align-items:center;gap:16px}.l-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.hero,.grid{display:grid;grid-template-columns:1.15fr .85fr;gap:20px;margin-top:24px}.panel{background:var(--panel,#fff);border:1px solid rgba(90,80,60,.14);border-radius:28px;padding:26px}.hero h1{font-size:clamp(42px,6vw,70px);line-height:.97;margin:6px 0 16px}.notice{padding:14px 16px;border-radius:16px;background:rgba(70,100,150,.08);margin-top:14px}.warn{background:rgba(160,90,50,.09)}.code{font-family:ui-monospace,monospace;font-size:26px;letter-spacing:.08em;font-weight:700}.small{font-size:13px;line-height:1.5;opacity:.72}.forms{display:grid;grid-template-columns:1fr 1fr;gap:16px}.field{display:flex;flex-direction:column;gap:7px}.league-card{display:block;border:1px solid rgba(90,80,60,.13);border-radius:18px;padding:16px;margin-top:10px;text-decoration:none;color:inherit}.league-card strong{font-size:22px}.league-card span{display:block;margin-top:5px;opacity:.66}.pill{display:inline-flex;border:1px solid rgba(90,80,60,.16);border-radius:999px;padding:6px 9px;font-size:11px}.empty{opacity:.65}@media(max-width:760px){.hero,.grid,.forms{grid-template-columns:1fr}.panel{padding:20px}}
</style></head><body><main class="l-wrap"><header class="l-head"><a class="brand" href="<?=h(route_url('home'))?>"><span class="brand-mark">उ</span><span>Udaan Leagues</span></a><div class="l-actions"><a class="ghost" href="<?=h(app_url('connect'))?>">Connect</a><a class="ghost" href="<?=h(app_url('today'))?>">Today</a><a class="ghost" href="<?=h(app_url('coach'))?>">Coach</a><?=theme_toggle()?></div></header>

<section class="hero"><div class="panel"><p class="eyebrow">PRIVATE LEAGUES · V0.15 PILOT</p><h1>Compete as teams, without rewarding grind.</h1><p class="lead">League scoring uses real completed Missions, but each member can contribute at most three active Arena-days per match. Team scores are normalized by team size.</p><?php if(!$enabled):?><div class="notice warn"><strong>League features are unavailable for under-13 Players in this release.</strong><p class="small">Udaan requires a future verified parent/institution consent model before enabling social competition for this age group.</p></div><?php endif;?><?php if($flash):?><div class="notice"><strong><?=h((string)($flash['message']??'Updated.'))?></strong><?php if(!empty($flash['code'])):?><div class="code"><?=h((string)$flash['code'])?></div><p class="small">This one-time team-league code expires in 7 days and is not stored in plaintext.</p><?php endif;?></div><?php endif;?></div>
<aside class="panel"><p class="eyebrow">FAIR SCORE RULE</p><p><span class="pill">0–100 normalized score</span> <span class="pill">3 active days/member max</span></p><p class="small">A larger team does not gain an automatic scoring advantage. There is no per-member public rank, speed bonus or paid boost. Season awards include participation, consistency and improvement—not only champion.</p></aside></section>

<?php if($enabled):?><section class="grid"><div class="panel"><p class="eyebrow">CREATE PRIVATE LEAGUE</p><h2>Start from a team you own</h2><?php if(!$ownedTeams):?><p class="empty">Create a team in Connect before starting a league.</p><?php else:?><form method="post" action="<?=h(app_url('league/action'))?>"><input type="hidden" name="csrf" value="<?=h(global_csrf())?>"><input type="hidden" name="action" value="create_league"><div class="field"><label>LEAGUE NAME</label><input name="league_name" maxlength="40" required placeholder="e.g. Biology Weekend League"></div><div class="field"><label>YOUR TEAM</label><select name="team_id"><?php foreach($ownedTeams as$t):?><option value="<?=h((string)$t['id'])?>"><?=h((string)$t['name'])?></option><?php endforeach;?></select></div><div class="field"><label>ARENA</label><select name="arena"><?php foreach($arenas as$key=>$label):?><option value="<?=h($key)?>"><?=h($label)?></option><?php endforeach;?></select></div><button class="primary" style="margin-top:14px">Create private league →</button></form><?php endif;?></div>

<div class="panel"><p class="eyebrow">JOIN LEAGUE</p><h2>Enter a team you own</h2><?php if(!$ownedTeams):?><p class="empty">You need to own a team to enter it into a league.</p><?php else:?><form method="post" action="<?=h(app_url('league/action'))?>"><input type="hidden" name="csrf" value="<?=h(global_csrf())?>"><input type="hidden" name="action" value="join_league"><div class="field"><label>TEAM</label><select name="team_id"><?php foreach($ownedTeams as$t):?><option value="<?=h((string)$t['id'])?>"><?=h((string)$t['name'])?></option><?php endforeach;?></select></div><div class="field"><label>LEAGUE CODE</label><input name="code" maxlength="20" autocomplete="off" required placeholder="16-character code"></div><button class="primary" style="margin-top:14px">Join league →</button></form><?php endif;?></div></section>

<section class="panel" style="margin-top:20px"><p class="eyebrow">YOUR LEAGUES</p><h2>Private team competitions</h2><?php if(!$leagues):?><p class="empty">No leagues yet.</p><?php else:?><?php foreach($leagues as$l):$season=is_array($l['season']??null)?$l['season']:null;?><a class="league-card" href="<?=h(app_url('league/'.rawurlencode((string)$l['id'])))?>"><strong><?=h((string)$l['name'])?></strong><span><?=count((array)$l['teams'])?> teams · <?=h($arenas[$l['arena']]??ucfirst((string)$l['arena']))?> · <?=h(udaan_competition_divisions()[$l['division']]??'Foundation')?><?php if($season):?> · season <?=h(udaan_competition_season_status($season,today_key()))?><?php endif;?></span></a><?php endforeach;?><?php endif;?></section><?php endif;?>
</main><?=common_theme_script()?></body></html>
