<?php
require __DIR__.'/bootstrap.php';

$identity=udaan_player_session_identity();$player=$identity?$store->getPlayer($identity):null;
if(!$identity||!is_array($player)||empty($player['onboarding_completed'])){header('Location: '.app_url('player'));exit;}
if(!udaan_social_enabled_for_player($player)){http_response_code(403);exit('Competition features are unavailable for under-13 Players in this release.');}

$leagueId=(string)($_GET['league']??'');
if(!preg_match('/^[0-9a-f-]{36}$/i',$leagueId)){http_response_code(404);exit('League not found.');}
$state=$store->getCompetitionState();$league=udaan_competition_league($state,$leagueId,$identity,$store);
if(!is_array($league)){http_response_code(404);exit('League not found.');}

$social=$store->getSocialGraph();$arenas=udaan_player_arenas();$divisions=udaan_competition_divisions();
$isCreator=((string)($league['created_by_identity']??'')===$identity);
$season=is_array($league['season']??null)?$league['season']:null;
$standings=$season?udaan_competition_standings($store,$league,today_key()):[];
$awards=$season?udaan_competition_awards($standings):[];
$matches=[];
if($season)foreach((array)($season['matches']??[]) as$m)if(is_array($m))$matches[]=udaan_competition_match_result($store,$league,$m,today_key());
usort($matches,fn($a,$b)=>strcmp((string)($a['match']['start_date']??''),(string)($b['match']['start_date']??'')));
$session=&udaan_session();$flash=is_array($session['competition_flash']??null)?$session['competition_flash']:null;unset($session['competition_flash']);
function league_team_name(array $social,string $teamId): string {return (string)($social['teams'][$teamId]['name']??'Team');}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h((string)$league['name'])?> · Udaan League</title><?=common_assets_head()?><style>
.g-wrap{max-width:1180px;margin:0 auto;padding:24px 20px 72px}.g-head{display:flex;justify-content:space-between;align-items:center;gap:16px}.g-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.hero,.grid{display:grid;grid-template-columns:1.2fr .8fr;gap:20px;margin-top:24px}.panel{background:var(--panel,#fff);border:1px solid rgba(90,80,60,.14);border-radius:28px;padding:26px}.hero h1{font-size:clamp(42px,6vw,68px);line-height:.97;margin:6px 0 16px}.notice{padding:14px 16px;border-radius:16px;background:rgba(70,100,150,.08);margin-top:14px}.code{font-family:ui-monospace,monospace;font-size:26px;letter-spacing:.08em;font-weight:700}.pill{display:inline-flex;border:1px solid rgba(90,80,60,.16);border-radius:999px;padding:6px 9px;font-size:11px}.small{font-size:13px;line-height:1.5;opacity:.72}.row{display:grid;grid-template-columns:54px 1fr repeat(4,72px);gap:10px;align-items:center;padding:12px 0;border-bottom:1px solid rgba(90,80,60,.1)}.row:last-child{border-bottom:0}.match{border:1px solid rgba(90,80,60,.13);border-radius:18px;padding:16px;margin-top:12px}.match-score{font-size:34px;font-weight:700}.teams{display:grid;grid-template-columns:1fr auto 1fr;gap:12px;align-items:center}.teams>div:last-child{text-align:right}.award-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px;margin-top:14px}.award{border:1px solid rgba(90,80,60,.12);border-radius:16px;padding:14px}.award strong{display:block}.score-rule{line-height:1.6}.table-head{font-size:11px;opacity:.6}@media(max-width:780px){.hero,.grid,.award-grid{grid-template-columns:1fr}.row{grid-template-columns:40px 1fr 54px 54px}.row>*:nth-child(5),.row>*:nth-child(6){display:none}.panel{padding:20px}}
</style></head><body><main class="g-wrap"><header class="g-head"><a class="brand" href="<?=h(app_url('leagues'))?>"><span class="brand-mark">उ</span><span>Udaan League</span></a><div class="g-actions"><a class="ghost" href="<?=h(app_url('leagues'))?>">Leagues</a><a class="ghost" href="<?=h(app_url('connect'))?>">Connect</a><a class="ghost" href="<?=h(app_url('today'))?>">Today</a><?=theme_toggle()?></div></header>

<section class="hero"><div class="panel"><p class="eyebrow">PRIVATE <?=h(strtoupper($divisions[$league['division']]??'Foundation'))?> DIVISION</p><h1><?=h((string)$league['name'])?></h1><p class="lead"><?=h($arenas[$league['arena']]??ucfirst((string)$league['arena']))?> team league · <?=count((array)$league['teams'])?> teams. Rankings are private to participating teams in this pilot.</p><?php if($flash):?><div class="notice"><strong><?=h((string)($flash['message']??'Updated.'))?></strong><?php if(!empty($flash['code'])):?><div class="code"><?=h((string)$flash['code'])?></div><p class="small">One-time league invite. It expires in 7 days and is not stored in plaintext.</p><?php endif;?></div><?php endif;?></div>
<aside class="panel"><p class="eyebrow">SCORE RULE</p><p class="score-rule"><strong>Each member contributes up to 3 active Arena-days per match.</strong><br>Team score = contributed active days ÷ (members × 3), normalized to 0–100. Win = 3 table points, draw = 1 each, loss = 0.</p><p class="small">No speed bonus, no paid boost, no individual public rank and no advantage from simply adding more team members.</p><?php if($isCreator&&!$season):?><form method="post" action="<?=h(app_url('league/action'))?>"><input type="hidden" name="csrf" value="<?=h(global_csrf())?>"><input type="hidden" name="action" value="create_invite"><input type="hidden" name="league_id" value="<?=h($leagueId)?>"><button class="ghost">Create team invite →</button></form><?php if(count((array)$league['teams'])>=2):?><form method="post" action="<?=h(app_url('league/action'))?>" style="margin-top:10px"><input type="hidden" name="csrf" value="<?=h(global_csrf())?>"><input type="hidden" name="action" value="start_season"><input type="hidden" name="league_id" value="<?=h($leagueId)?>"><button class="primary">Start season today →</button></form><?php endif;?><?php endif;?></aside></section>

<section class="grid"><div class="panel"><p class="eyebrow">TEAMS</p><h2>Participating teams</h2><?php foreach(array_keys((array)$league['teams']) as$teamId):?><div class="match"><strong><?=h(league_team_name($social,(string)$teamId))?></strong><br><small><?=count((array)($social['teams'][$teamId]['members']??[]))?> members</small></div><?php endforeach;?></div>
<div class="panel"><p class="eyebrow">SEASON</p><?php if(!$season):?><h2>Season not started</h2><p class="small">The league creator can start once at least two teams have joined.</p><?php else:?><h2>Season 1 · <?=h(udaan_competition_season_status($season,today_key()))?></h2><p><?=h((string)$season['start_date'])?> → <?=h((string)$season['end_date'])?></p><p class="small"><?=count((array)$season['matches'])?> round-robin matches. Division: <?=h($divisions[$season['division']]??'Foundation')?>.</p><?php endif;?></div></section>

<?php if($season):?><section class="panel" style="margin-top:20px"><p class="eyebrow">TEAM STANDINGS</p><h2>Season table</h2><?php if(!$standings):?><p class="small">Standings begin after the first match completes.</p><?php else:?><div class="row table-head"><span>#</span><span>TEAM</span><span>PTS</span><span>W</span><span>AVG</span><span>PART.</span></div><?php foreach($standings as$r):?><div class="row"><strong><?=intval($r['position'])?></strong><strong><?=h((string)$r['name'])?></strong><strong><?=intval($r['points'])?></strong><span><?=intval($r['wins'])?></span><span><?=intval($r['average_score'])?></span><span><?=intval($r['average_participation'])?>%</span></div><?php endforeach;?><?php endif;?></section>

<section class="grid"><div class="panel"><p class="eyebrow">MATCHES</p><h2>Round-robin schedule</h2><?php foreach($matches as$result):$m=$result['match'];?><article class="match"><div class="teams"><div><strong><?=h(league_team_name($social,(string)$m['team_a']))?></strong><div class="match-score"><?=intval($result['team_a']['score'])?></div></div><span class="pill"><?=h(strtoupper((string)$result['status']))?></span><div><strong><?=h(league_team_name($social,(string)$m['team_b']))?></strong><div class="match-score"><?=intval($result['team_b']['score'])?></div></div></div><p class="small">Round <?=intval($m['round'])?> · <?=h((string)$m['start_date'])?> to <?=h((string)$m['end_date'])?> · participation <?=intval($result['team_a']['participation_rate'])?>% vs <?=intval($result['team_b']['participation_rate'])?>%</p></article><?php endforeach;?></div>
<div class="panel"><p class="eyebrow">MULTIPLE AWARDS</p><h2>More than one way to succeed</h2><?php if(!$awards):?><p class="small">Awards appear once at least one match has completed.</p><?php else:?><div class="award-grid"><?php foreach($awards as$a):?><article class="award"><small><?=h((string)$a['label'])?></small><strong><?=h((string)$a['team_name'])?></strong><span><?=intval($a['value'])?> <?=h((string)$a['unit'])?></span></article><?php endforeach;?></div><?php endif;?><p class="small">Champion recognizes match results. Separate awards recognize participation, consistency and improvement so the season is not reduced to one winner.</p></div></section><?php endif;?>
</main><?=common_theme_script()?></body></html>
