<?php
require __DIR__.'/bootstrap.php';

$identity=udaan_player_session_identity();
$player=$identity?$store->getPlayer($identity):null;
if(!$identity||!is_array($player)||empty($player['onboarding_completed'])){header('Location: '.app_url('player'));exit;}

$date=today_key();
$state=udaan_mission_ensure_daily($store,$identity,$player,$date);
$window=udaan_performance_window($state,14,$date);
$month=udaan_performance_window($state,30,$date);
$bests=udaan_performance_personal_bests($state);
$readinessState=$store->getReadinessState($identity);
$readinessHistory=udaan_daily_readiness_history($readinessState,14);
$fit14=udaan_fit_summary($state,14,$date);
$fit30=udaan_fit_summary($state,30,$date);
$arenas=udaan_player_arenas();
$maxDay=max(1,...array_map(fn($r)=>(int)($r['completed']??0),$window['daily']));
$topArena='—';$topArenaCompleted=0;
foreach($window['arena_stats'] as $arena=>$stat){
    if((int)($stat['completed']??0)>$topArenaCompleted){$topArena=$arenas[$arena]??ucfirst($arena);$topArenaCompleted=(int)$stat['completed'];}
}
function performance_date_label(?string $date): string {
    if(!$date)return '—';$ts=strtotime($date);return $ts?date('j M',$ts):$date;
}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Progress · Udaan</title><?=common_assets_head()?><style>
.progress-wrap{max-width:1180px;margin:0 auto;padding:24px 20px 72px}.progress-head{display:flex;justify-content:space-between;align-items:center;gap:16px}.progress-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.hero{margin-top:34px;display:grid;grid-template-columns:1.35fr .65fr;gap:20px}.panel{background:var(--panel,#fff);border:1px solid rgba(90,80,60,.14);border-radius:28px;padding:26px}.hero h1{font-size:clamp(42px,6vw,72px);line-height:.96;margin:6px 0 16px}.metrics{display:grid;grid-template-columns:repeat(4,1fr);gap:14px;margin-top:20px}.metric strong{display:block;font-size:38px;line-height:1}.metric small{display:block;margin-top:7px;opacity:.65}.graph{display:grid;grid-template-columns:repeat(14,1fr);gap:8px;align-items:end;height:210px;margin-top:26px}.day{display:flex;flex-direction:column;justify-content:flex-end;align-items:center;gap:8px;height:100%}.bar-wrap{height:150px;width:100%;display:flex;align-items:flex-end;justify-content:center}.bar{width:min(28px,80%);min-height:4px;border-radius:999px 999px 5px 5px;background:currentColor;opacity:.78}.day small{font-size:10px;opacity:.62;white-space:nowrap}.arena-grid,.best-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:16px;margin-top:20px}.arena-row{display:flex;justify-content:space-between;gap:16px;padding:12px 0;border-bottom:1px solid rgba(90,80,60,.12)}.arena-row:last-child{border-bottom:0}.best-card strong{font-size:42px;display:block}.privacy{font-size:13px;opacity:.68;line-height:1.55}.readiness-strip{display:grid;grid-template-columns:repeat(7,1fr);gap:10px;margin-top:18px}.readiness-day{padding:12px;border:1px solid rgba(90,80,60,.12);border-radius:16px}.readiness-day strong{display:block;margin-top:5px}.readiness-day.low{background:rgba(160,90,50,.08)}.readiness-day.balanced{background:rgba(70,100,150,.07)}.readiness-day.high{background:rgba(50,120,80,.08)}.empty{opacity:.7}@media(max-width:850px){.hero,.metrics,.arena-grid,.best-grid{grid-template-columns:1fr 1fr}.readiness-strip{grid-template-columns:repeat(4,1fr)}.graph{gap:4px}.panel{padding:20px}}@media(max-width:560px){.hero,.metrics,.arena-grid,.best-grid{grid-template-columns:1fr}.readiness-strip{grid-template-columns:repeat(2,1fr)}.graph{overflow-x:auto;grid-template-columns:repeat(14,34px);justify-content:start}.progress-head{align-items:flex-start}}
</style></head><body><main class="progress-wrap"><header class="progress-head"><a class="brand" href="<?=h(route_url('home'))?>"><span class="brand-mark">उ</span><span>Udaan</span></a><div class="progress-actions"><a class="ghost" href="<?=h(app_url('today'))?>">Today</a><a class="ghost" href="<?=h(app_url('fit'))?>">Fit</a><a class="ghost" href="<?=h(app_url('readiness'))?>">Readiness</a><a class="ghost" href="<?=h(app_url('player'))?>">Player</a><?=theme_toggle()?></div></header>

<section class="hero"><div class="panel"><p class="eyebrow">PERFORMANCE GRAPH · 14 DAYS</p><h1>Your progress comes from what you actually complete.</h1><p class="lead">Udaan tracks training behaviour across your selected Arenas. There is no synthetic overall student score and no health/readiness scoring in this release.</p><div class="metrics"><div class="metric"><strong><?=$window['training_days']?></strong><small>training days</small></div><div class="metric"><strong><?=$window['completed']?></strong><small>missions completed</small></div><div class="metric"><strong><?=$window['minutes']?></strong><small>completed minutes</small></div><div class="metric"><strong><?=$window['completion_rate']?>%</strong><small>mission completion</small></div></div></div><aside class="panel"><p class="eyebrow">30-DAY VIEW</p><div class="metric"><strong><?=$month['training_days']?></strong><small>meaningful training days</small></div><div class="metric" style="margin-top:22px"><strong><?=$month['completed']?></strong><small>completed missions</small></div><div class="metric" style="margin-top:22px"><strong><?=h($topArena)?></strong><small>most active Arena · last 14 days</small></div><p class="privacy">Performance is derived from private Mission history. Reflection text is not collected. Future health/readiness information will remain a separate private signal rather than being folded into one score.</p></aside></section>

<section class="panel" style="margin-top:20px"><p class="eyebrow">DAILY TRAINING</p><h2>Fourteen-day activity</h2><div class="graph"><?php foreach($window['daily'] as$row):$count=(int)$row['completed'];$height=max(4,(int)round(($count/$maxDay)*145));?><div class="day" title="<?=h((string)$row['date'])?> · <?=$count?> completed"><div class="bar-wrap"><div class="bar" style="height:<?=$height?>px;opacity:<?=$count?'.82':'.16'?>"></div></div><small><?=h(date('j M',strtotime((string)$row['date'])))?></small></div><?php endforeach;?></div></section>

<section class="panel" style="margin-top:20px"><p class="eyebrow">UDAAN FIT · CONSISTENCY</p><h2>Movement that supports the rest of your training</h2><div class="metrics"><div class="metric"><strong><?=$fit14['active_days']?></strong><small>active days · 14d</small></div><div class="metric"><strong><?=$fit14['minutes']?></strong><small>movement minutes · 14d</small></div><div class="metric"><strong><?=$fit30['active_days']?></strong><small>active days · 30d</small></div><div class="metric"><strong><?=$fit14['consistency_rate']?>%</strong><small>14-day consistency</small></div></div><p class="privacy">Fit tracks completed movement sessions only. No calories, body weight, body comparison or weight-loss ranking.</p></section>

<section class="panel" style="margin-top:20px"><p class="eyebrow">READINESS HISTORY · PRIVATE</p><h2>A separate signal, not a performance score</h2><p class="privacy">Readiness helps tune workload. It is never combined with Mission completion, Personal Bests or academic ranking.</p><?php if(!$readinessHistory):?><p class="empty">No readiness check-ins yet.</p><?php else:?><div class="readiness-strip"><?php foreach($readinessHistory as$row):$band=(string)($row['band']??'balanced');?><div class="readiness-day <?=h(in_array($band,['low','balanced','high'],true)?$band:'balanced')?>"><small><?=h(performance_date_label((string)($row['date']??'')))?></small><strong><?=h((string)($row['label']??ucfirst($band).' readiness'))?></strong></div><?php endforeach;?></div><?php endif;?></section>

<section class="arena-grid"><div class="panel"><p class="eyebrow">ARENA BREAKDOWN</p><h2>Where you trained</h2><?php if(!$window['arena_stats']):?><p class="empty">Complete your first mission to start the graph.</p><?php else:?><?php foreach($window['arena_stats'] as$arena=>$stat):?><div class="arena-row"><div><strong><?=h($arenas[$arena]??ucfirst($arena))?></strong><br><small><?=intval($stat['minutes']??0)?> completed minutes</small></div><strong><?=intval($stat['completed']??0)?></strong></div><?php endforeach;?><?php endif;?></div><div class="panel"><p class="eyebrow">ALL-TIME RECORDS</p><h2>Personal Bests</h2><div class="best-grid"><div class="best-card"><strong><?=intval($bests['best_completed_day']['value']??0)?></strong><span>missions in one day</span><small> · <?=h(performance_date_label($bests['best_completed_day']['date']??null))?></small></div><div class="best-card"><strong><?=intval($bests['best_minutes_day']['value']??0)?></strong><span>minutes in one day</span><small> · <?=h(performance_date_label($bests['best_minutes_day']['date']??null))?></small></div><div class="best-card"><strong><?=intval($bests['training_days']??0)?></strong><span>training days</span></div><div class="best-card"><strong><?=intval($bests['all_time_completed']??0)?></strong><span>missions completed</span></div></div></div></section>
</main><?=common_theme_script()?></body></html>
