<?php
require __DIR__.'/bootstrap.php';

$identity=udaan_player_session_identity();$player=$identity?$store->getPlayer($identity):null;
if(!$identity||!is_array($player)||empty($player['onboarding_completed'])){header('Location: '.app_url('player'));exit;}
if(!udaan_social_enabled_for_player($player)){http_response_code(403);exit('Social features are unavailable for under-13 Players in this release.');}

$teamId=(string)($_GET['team']??'');
if(!preg_match('/^[0-9a-f-]{36}$/i',$teamId)){http_response_code(404);exit('Team not found.');}
$graph=$store->getSocialGraph();$team=udaan_social_team($graph,$teamId,$identity);
if(!is_array($team)){http_response_code(404);exit('Team not found.');}
$members=udaan_social_team_members($store,$team);
$progress=udaan_social_team_challenge_progress($store,$team);
$isOwner=(($team['members'][$identity]['role']??'member')==='owner');
$arenas=udaan_player_arenas();
$commonArenas=udaan_social_team_common_arenas($store,$team);
$session=&udaan_session();$flash=is_array($session['social_flash']??null)?$session['social_flash']:null;unset($session['social_flash']);
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title><?=h((string)$team['name'])?> · Udaan Team</title><?=common_assets_head()?><style>
.team-wrap{max-width:1080px;margin:0 auto;padding:24px 20px 72px}.team-head{display:flex;justify-content:space-between;align-items:center;gap:16px}.team-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.hero,.grid{display:grid;grid-template-columns:1.2fr .8fr;gap:20px;margin-top:24px}.panel{background:var(--panel,#fff);border:1px solid rgba(90,80,60,.14);border-radius:28px;padding:26px}.hero h1{font-size:clamp(42px,6vw,68px);line-height:.97;margin:6px 0 16px}.notice{padding:14px 16px;border-radius:16px;background:rgba(70,100,150,.08);margin-top:14px}.code{font-family:ui-monospace,monospace;font-size:26px;letter-spacing:.08em;font-weight:700}.row{display:flex;justify-content:space-between;gap:16px;align-items:center;padding:13px 0;border-bottom:1px solid rgba(90,80,60,.11)}.row:last-child{border-bottom:0}.pill{display:inline-flex;border:1px solid rgba(90,80,60,.16);border-radius:999px;padding:6px 9px;font-size:11px}.progress{font-size:56px;font-weight:700;line-height:1}.bar{height:10px;border-radius:999px;background:rgba(90,80,60,.12);overflow:hidden;margin:12px 0}.bar>span{display:block;height:100%;background:currentColor}.small{font-size:13px;line-height:1.5;opacity:.72}@media(max-width:760px){.hero,.grid{grid-template-columns:1fr}.panel{padding:20px}}
</style></head><body><main class="team-wrap"><header class="team-head"><a class="brand" href="<?=h(app_url('connect'))?>"><span class="brand-mark">उ</span><span>Udaan Team</span></a><div class="team-actions"><a class="ghost" href="<?=h(app_url('connect'))?>">Connect</a><a class="ghost" href="<?=h(app_url('today'))?>">Today</a><a class="ghost" href="<?=h(app_url('coach'))?>">Coach</a><?=theme_toggle()?></div></header>

<section class="hero"><div class="panel"><p class="eyebrow">PRIVATE TEAM · <?=count($members)?> / 8 MEMBERS</p><h1><?=h((string)$team['name'])?></h1><p class="lead">Small invite-only team. No public directory, follower counts, open chat or member ranking.</p><?php if($flash):?><div class="notice"><strong><?=h((string)($flash['message']??'Updated.'))?></strong><?php if(!empty($flash['code'])):?><div class="code"><?=h((string)$flash['code'])?></div><p class="small">This one-time code expires in 7 days and is not stored in plaintext.</p><?php endif;?></div><?php endif;?></div>
<aside class="panel"><p class="eyebrow">TEAM CONTROLS</p><?php if($isOwner):?><form method="post" action="<?=h(app_url('team/action'))?>"><input type="hidden" name="csrf" value="<?=h(global_csrf())?>"><input type="hidden" name="action" value="create_invite"><input type="hidden" name="team_id" value="<?=h($teamId)?>"><button class="primary">Create one-time join code →</button></form><p class="small">Only the owner can create team invites or start a team challenge in v1.</p><?php else:?><form method="post" action="<?=h(app_url('team/action'))?>"><input type="hidden" name="csrf" value="<?=h(global_csrf())?>"><input type="hidden" name="action" value="leave"><input type="hidden" name="team_id" value="<?=h($teamId)?>"><button class="ghost">Leave team</button></form><p class="small">Leaving removes your membership immediately. Your private Mission history stays yours.</p><?php endif;?></aside></section>

<section class="grid"><div class="panel"><p class="eyebrow">MEMBERS</p><h2>Nicknames only</h2><?php foreach($members as$m):?><div class="row"><div><strong><?=h((string)$m['nickname'])?></strong><br><small><?=h((string)$m['role'])?></small></div><span class="pill"><?=((string)($m['player_id']??'')===(string)($player['id']??''))?'You':'Member'?></span></div><?php endforeach;?></div>
<div class="panel"><p class="eyebrow">TEAM CHALLENGE</p><?php if(!empty($progress['active'])):$ch=$progress['challenge'];?><h2><?=h($arenas[$ch['arena']]??ucfirst((string)$ch['arena']))?> participation week</h2><div class="progress"><?=intval($progress['participants'])?> / <?=intval($progress['members'])?></div><div class="bar"><span style="width:<?=intval($progress['completion_rate'])?>%"></span></div><p class="small">Each member participates by completing at least one real <?=h($arenas[$ch['arena']]??ucfirst((string)$ch['arena']))?> Mission between <?=h((string)$ch['start_date'])?> and <?=h((string)$ch['end_date'])?>. There is no speed bonus or top-member rank.</p><?php foreach((array)$progress['rows'] as$r):?><div class="row"><strong><?=h((string)$r['nickname'])?></strong><span class="pill"><?=!empty($r['completed'])?'Participated':'Not yet'?></span></div><?php endforeach;?><?php elseif($isOwner):?><h2>Start a participation week</h2><?php if($commonArenas):?><form method="post" action="<?=h(app_url('team/action'))?>"><input type="hidden" name="csrf" value="<?=h(global_csrf())?>"><input type="hidden" name="action" value="create_challenge"><input type="hidden" name="team_id" value="<?=h($teamId)?>"><label>SHARED ARENA</label><select name="arena"><?php foreach($commonArenas as$key):?><option value="<?=h($key)?>"><?=h($arenas[$key]??ucfirst($key))?></option><?php endforeach;?></select><button class="primary" style="margin-top:14px">Start 7-day team challenge →</button></form><p class="small">Only Arenas enabled by every current member can be used. Challenge success means participation, not competition inside the team.</p><?php else:?><p class="small">This team has no Arena enabled by every member yet, so a fair team challenge cannot start.</p><?php endif;?><?php else:?><h2>No active team challenge.</h2><p class="small">The team owner can start a simple 7-day participation challenge.</p><?php endif;?></div></section>
</main><?=common_theme_script()?></body></html>