<?php
require __DIR__.'/bootstrap.php';
$identity=udaan_player_session_identity();$player=$identity?$store->getPlayer($identity):null;
if(!$identity||!is_array($player)||empty($player['onboarding_completed'])){header('Location: '.app_url('player'));exit;}
$goals=udaan_player_goals();$arenas=udaan_player_arenas();$languages=udaan_player_languages();
$arenaLabels=[];foreach((array)($player['arenas']??[]) as$a)if(isset($arenas[$a]))$arenaLabels[]=$arenas[$a];
$goalLabel=$goals[$player['main_goal']??'general']??'General learning';
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Today · Udaan</title><?=common_assets_head()?><style>
.today-wrap{max-width:1160px;margin:0 auto;padding:24px 20px 72px}.today-head{display:flex;justify-content:space-between;align-items:center;gap:16px}.today-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.today-hero{margin-top:34px;display:grid;grid-template-columns:1.35fr .65fr;gap:22px}.today-panel{background:var(--panel,#fff);border:1px solid rgba(90,80,60,.14);border-radius:28px;padding:28px}.today-hero h1{font-size:clamp(42px,6vw,74px);line-height:.95;margin:6px 0 16px}.goal-strip{display:flex;gap:8px;flex-wrap:wrap;margin-top:18px}.goal-strip span{padding:8px 12px;border-radius:999px;border:1px solid rgba(90,80,60,.15);font-size:13px}.today-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:18px;margin-top:22px}.mission-card{display:flex;flex-direction:column;min-height:230px}.mission-card h2{font-size:28px;margin:8px 0}.mission-card p{line-height:1.55;flex:1}.status-now{color:#276b52;font-weight:700}.status-next{opacity:.65;font-weight:700}.privacy-mini{font-size:13px;line-height:1.5;opacity:.75}.player-meta strong{display:block;font-size:34px;margin:6px 0 10px}@media(max-width:850px){.today-hero,.today-grid{grid-template-columns:1fr}}
</style></head><body><main class="today-wrap"><header class="today-head"><a class="brand" href="<?=h(route_url('home'))?>"><span class="brand-mark">उ</span><span>Udaan</span></a><div class="today-actions"><a class="ghost" href="<?=h(app_url('player'))?>">Edit Player</a><?=theme_toggle()?></div></header><section class="today-hero"><div class="today-panel"><p class="eyebrow">TODAY · PLAYER FOUNDATION</p><h1>Hello, <?=h((string)$player['nickname'])?>.</h1><p class="lead">Your Udaan is now anchored to one Player profile. Today shows what is available now while the Mission and Performance engines are built on this same foundation.</p><div class="goal-strip"><span><?=h($goalLabel)?></span><span><?=intval($player['daily_minutes'])?> min/day</span><?php foreach($arenaLabels as$label):?><span><?=h($label)?></span><?php endforeach;?></div></div><aside class="today-panel player-meta"><p class="eyebrow">YOUR DIRECTION</p><strong><?=h((string)($player['exam_target']?:$goalLabel))?></strong><p><?=h($languages[$player['language']]??'English')?> · <?=h(udaan_player_stages()[$player['stage']]??'Learner')?></p><p class="privacy-mini">Profile visibility: private · Parent/institution sharing: off</p></aside></section><section class="today-grid"><article class="today-panel mission-card"><p class="eyebrow status-now">AVAILABLE NOW</p><h2>Daily 9</h2><p>Nine verified ideas across Udaan's learning pillars. Existing no-repeat history, signed packs and offline learning continue unchanged.</p><a class="primary" href="<?=h(app_url('daily'))?>">Start Daily 9 →</a></article><article class="today-panel mission-card"><p class="eyebrow status-next">FOUNDATION READY</p><h2>Your future Missions</h2><p>The Player now carries your goal, available time and Arena choices. v0.8 will assign real missions through one universal Mission Engine instead of separate task systems.</p><a class="ghost" href="<?=h(app_url('player'))?>">Review my goals →</a></article><article class="today-panel mission-card"><p class="eyebrow status-next">NEXT PERFORMANCE LAYER</p><h2>Progress without fake scores</h2><p>Udaan will build Knowledge, Accuracy, Consistency, Revision, Focus and other dimensions from real events. No fabricated overall “student score” is shown in this foundation release.</p><span class="ghost">Event ledger active</span></article></section></main><?=common_theme_script()?></body></html>