<?php
require __DIR__.'/bootstrap.php';

$identity=udaan_player_session_identity();$player=$identity?$store->getPlayer($identity):null;
if(!$identity||!is_array($player)||empty($player['onboarding_completed'])){header('Location: '.app_url('player'));exit;}

$date=today_key();
$state=udaan_mission_ensure_daily($store,$identity,$player,$date);
$missions=udaan_missions_for_date($state,$date);
$history=udaan_mission_history($state,18);
$history=array_values(array_filter($history,fn($m)=>($m['scheduled_date']??'')!==$date));
$completed=count(array_filter($missions,fn($m)=>($m['status']??'')==='completed'));
$skipped=count(array_filter($missions,fn($m)=>($m['status']??'')==='skipped'));
$total=count($missions);

$goals=udaan_player_goals();$arenas=udaan_player_arenas();$languages=udaan_player_languages();
$goalLabel=$goals[$player['main_goal']??'general']??'General learning';
$arenaLabels=[];foreach((array)($player['arenas']??[]) as$a)if(isset($arenas[$a]))$arenaLabels[]=$arenas[$a];
$statusMessage=isset($_GET['mission'])?($_GET['mission']==='complete'?'Mission completed.':'Mission skipped for today.'):'';
function mission_status_label(array $m): string {$s=(string)($m['status']??'assigned');return match($s){'completed'=>'Completed','skipped'=>'Skipped','in_progress'=>'In progress',default=>'Ready'};}
function mission_action_url(array $m,string $action): string {return app_url('mission/'.rawurlencode((string)$m['id']).'/'.$action);}
?><!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Today · Udaan</title><?=common_assets_head()?><style>
.today-wrap{max-width:1180px;margin:0 auto;padding:24px 20px 72px}.today-head{display:flex;justify-content:space-between;align-items:center;gap:16px}.today-actions{display:flex;gap:10px;align-items:center;flex-wrap:wrap}.today-hero{margin-top:34px;display:grid;grid-template-columns:1.35fr .65fr;gap:22px}.today-panel{background:var(--panel,#fff);border:1px solid rgba(90,80,60,.14);border-radius:28px;padding:28px}.today-hero h1{font-size:clamp(42px,6vw,74px);line-height:.95;margin:6px 0 16px}.goal-strip{display:flex;gap:8px;flex-wrap:wrap;margin-top:18px}.goal-strip span,.mission-meta span{padding:8px 12px;border-radius:999px;border:1px solid rgba(90,80,60,.15);font-size:13px}.progress-number{font-size:52px;line-height:1;font-weight:700}.mission-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:18px;margin-top:22px}.mission-card{display:flex;flex-direction:column;min-height:275px}.mission-card h2{font-size:30px;margin:8px 0}.mission-card p{line-height:1.55}.mission-meta{display:flex;gap:7px;flex-wrap:wrap;margin:8px 0 20px}.mission-actions{display:flex;gap:9px;align-items:center;flex-wrap:wrap;margin-top:auto}.mission-actions form{margin:0}.status-completed{color:#276b52;font-weight:700}.status-skipped{opacity:.65;font-weight:700}.status-ready{font-weight:700}.history{margin-top:24px}.history-row{display:grid;grid-template-columns:110px 1fr auto;gap:14px;padding:14px 0;border-bottom:1px solid rgba(90,80,60,.12);align-items:center}.history-row:last-child{border-bottom:0}.history-row small{opacity:.65}.notice{margin:18px 0 0;padding:12px 16px;border-radius:14px;background:rgba(39,107,82,.09)}.privacy-mini{font-size:13px;line-height:1.5;opacity:.75}.player-meta strong{display:block;font-size:34px;margin:6px 0 10px}.secondary-button{background:transparent;border:1px solid rgba(90,80,60,.22);border-radius:999px;padding:11px 15px;cursor:pointer;color:inherit}@media(max-width:850px){.today-hero,.mission-grid{grid-template-columns:1fr}.history-row{grid-template-columns:1fr}}
</style></head><body><main class="today-wrap"><header class="today-head"><a class="brand" href="<?=h(route_url('home'))?>"><span class="brand-mark">उ</span><span>Udaan</span></a><div class="today-actions"><a class="ghost" href="<?=h(app_url('progress'))?>">Progress</a><a class="ghost" href="<?=h(app_url('player'))?>">Edit Player</a><?=theme_toggle()?></div></header>
<section class="today-hero"><div class="today-panel"><p class="eyebrow">TODAY · UNIVERSAL MISSIONS</p><h1>Hello, <?=h((string)$player['nickname'])?>.</h1><p class="lead">Your missions come from one shared engine across learning, movement, focus and reflection. Completion records real activity; it does not create a fake overall score.</p><div class="goal-strip"><span><?=h($goalLabel)?></span><span><?=intval($player['daily_minutes'])?> min/day</span><?php foreach($arenaLabels as$label):?><span><?=h($label)?></span><?php endforeach;?></div><?php if($statusMessage):?><div class="notice"><?=h($statusMessage)?></div><?php endif;?></div>
<aside class="today-panel player-meta"><p class="eyebrow">TODAY'S PROGRESS</p><div class="progress-number"><?=$completed?> / <?=$total?></div><p>missions completed<?php if($skipped):?> · <?=$skipped?> skipped<?php endif;?></p><strong><?=h((string)($player['exam_target']?:$goalLabel))?></strong><p><?=h($languages[$player['language']]??'English')?> · <?=h(udaan_player_stages()[$player['stage']]??'Learner')?></p><p class="privacy-mini">Mission results are private runtime data. Reflection text is never requested or stored by this release.</p></aside></section>

<section class="mission-grid"><?php foreach($missions as$m):$status=(string)($m['status']??'assigned');$rule=(string)($m['completion_rule']['mode']??'self_report');?>
<article class="today-panel mission-card"><p class="eyebrow <?= $status==='completed'?'status-completed':($status==='skipped'?'status-skipped':'status-ready') ?>"><?=h(strtoupper(mission_status_label($m)))?> · <?=h(strtoupper((string)($m['arena']??'core')))?></p><h2><?=h((string)$m['title'])?></h2><p><?=h((string)$m['objective'])?></p><div class="mission-meta"><span><?=intval($m['duration_minutes']??0)?> min</span><span><?=h((string)($m['difficulty']??'standard'))?></span><span><?=h(udaan_mission_types()[$m['type']??'']??'Mission')?></span></div><div class="mission-actions">
<?php if(($m['type']??'')==='daily9'&&$status!=='completed'):?><a class="primary" href="<?=h(app_url('daily'))?>">Start Daily 9 →</a><?php elseif($rule==='self_report'&&$status!=='completed'&&$status!=='skipped'):?><form method="post" action="<?=h(mission_action_url($m,'complete'))?>"><input type="hidden" name="csrf" value="<?=h(global_csrf())?>"><button class="primary">Mark complete →</button></form><?php endif;?>
<?php if($status!=='completed'&&$status!=='skipped'):?><form method="post" action="<?=h(mission_action_url($m,'skip'))?>"><input type="hidden" name="csrf" value="<?=h(global_csrf())?>"><button class="secondary-button">Skip today</button></form><?php elseif($status==='skipped'&&($m['type']??'')==='daily9'):?><a class="ghost" href="<?=h(app_url('daily'))?>">Do it anyway →</a><?php endif;?>
<?php if($status==='completed'):?><span class="status-completed">✓ Complete</span><?php elseif($status==='skipped'):?><span class="status-skipped">Skipped without penalty</span><?php endif;?></div></article>
<?php endforeach;?></section>

<section class="today-panel history"><p class="eyebrow">MISSION HISTORY</p><h2>Recent training days</h2><?php if(!$history):?><p class="lead">Your mission history starts today.</p><?php else:?><?php foreach($history as$m):?><div class="history-row"><small><?=h((string)($m['scheduled_date']??''))?></small><div><strong><?=h((string)($m['title']??'Mission'))?></strong><br><small><?=h((string)($m['arena']??'core'))?> · <?=intval($m['duration_minutes']??0)?> min</small></div><span><?=h(mission_status_label($m))?></span></div><?php endforeach;?><?php endif;?></section>
</main><?=common_theme_script()?></body></html>