#!/usr/bin/env python3
import json, uuid, pathlib

OUT = pathlib.Path(__file__).resolve().parents[1] / 'data' / 'content' / 'cards.json'
NS = uuid.UUID('4d6b7bca-8ef2-5d83-a8f0-85ac2ea9684a')

PILLARS = [
('think','Think & Reason','THINK & REASON',[
('evidence','Evidence vs opinion','Evidence can be checked; an opinion expresses a judgement or preference.','Which statement is evidence rather than opinion?','The thermometer reads 30°C','Summer is the best season','This book feels inspiring','What should you ask before accepting a strong claim?','Look for evidence and how it was obtained.'),
('assumptions','Hidden assumptions','An assumption is something treated as true without being tested.','What is the best way to handle an important assumption?','Test it','Ignore it','Repeat it more confidently','What can an unnoticed assumption change?','Pause once today and name an assumption behind a decision.'),
('correlation','Correlation and causation','Two things changing together does not by itself prove that one caused the other.','If two trends rise together, what can you safely conclude first?','They are associated','One definitely caused the other','They must be identical','What extra question helps before claiming cause?','Ask what other factors could explain the pattern.'),
('sources','Source reliability','Reliable claims are easier to trust when the source is identifiable, relevant and supported by evidence.','Which source is usually strongest for an exam deadline?','The official exam authority','An anonymous forwarded message','A random comment','What makes a source worth checking twice?','Before sharing a claim, find its original source.'),
('estimate','Estimation','A quick estimate helps detect impossible or suspicious answers before detailed calculation.','Why estimate before calculating exactly?','To check whether an answer is reasonable','To avoid thinking','To make every answer larger','Where can estimation save time?','Estimate one quantity before using a calculator today.'),
('tradeoffs','Trade-offs','Many decisions improve one thing while costing something else, such as time, money or convenience.','A trade-off means…','Gaining one benefit while accepting a cost','Getting every benefit with no cost','Avoiding all choices','What should a fair comparison include?','For one decision, write one benefit and one cost.'),
('bias','Bias awareness','Bias can influence which information we notice, remember or prefer.','What is a useful response when evidence challenges your view?','Examine the evidence','Reject it immediately','Attack the person','How can you reduce confirmation bias?','Read one credible viewpoint that differs from your first instinct.'),
('counterexample','Counterexamples','One valid counterexample can show that a universal claim is false.','Which claim is easiest to challenge with one counterexample?','All birds can fly','Some birds migrate','Many birds have feathers','Why are counterexamples powerful?','When someone says “always,” try to find one exception.'),
('probability','Probability thinking','Probability describes uncertainty; unlikely events can still happen and likely events can still fail to happen.','A 70% chance means…','The event is likely but not guaranteed','The event must happen','The event cannot happen','How should probability affect confidence?','Replace “certain” with a probability when the outcome is uncertain.'),
('systems','Systems thinking','In a system, parts interact, so changing one part can create effects elsewhere.','Which question is most “systems thinking”?','What else changes if I change this?','Who can I blame?','Can I ignore the connections?','Where do feedback loops appear?','Trace one everyday system: input → process → output.'),
('cause','Cause and effect','Good causal explanations identify a mechanism, not just a sequence of events.','What strengthens a cause-and-effect explanation?','A plausible mechanism','A louder opinion','A coincidence alone','What is the difference between “after” and “because”?','For one event, list more than one possible cause.'),
('questions','Better questions','Clear questions define what you are trying to understand and make better answers possible.','Which question is most useful for learning?','What evidence would change my mind?','Why is everyone wrong?','Can I skip the details?','What makes a question productive?','Turn one vague question into a specific one today.')]),
('science','Science & Discovery','SCIENCE & DISCOVERY',[
('orbit','Orbits and gravity','An orbiting satellite is continually falling under gravity while moving sideways fast enough to keep missing Earth.','What keeps a satellite in orbit?','Forward motion plus gravity','No gravity at all','Air pushing it upward','What does orbit teach about motion?','Imagine changing orbital speed: predict what might happen.'),
('cells','Cells','Cells are the basic structural and functional units of living organisms.','Which is a basic unit of life?','Cell','Atom only','Mountain','Why do tissues contain many cells?','Look at a leaf or skin and remember it is built from cells.'),
('light','Light','Light can be reflected, absorbed or transmitted when it meets matter.','A mirror mainly demonstrates…','Reflection','Evaporation','Fermentation','Why do different materials look different?','Find one reflective, one transparent and one opaque object.'),
('electricity','Electric circuits','Electric current needs a closed conducting path to flow through a simple circuit.','Why does a simple bulb go off when the circuit opens?','The conducting path is broken','Gravity stops','The bulb forgets its charge','What makes a circuit complete?','Trace the closed path in one battery-powered device.'),
('climate','Weather and climate','Weather describes short-term atmospheric conditions; climate describes longer-term patterns.','Which describes climate?','Typical rainfall patterns over decades','Today’s afternoon shower','One gust of wind','Why does timescale matter?','Compare today’s weather with your region’s usual season.'),
('watercycle','Water cycle','Water moves through evaporation, condensation, precipitation and collection, powered largely by solar energy and gravity.','What drives evaporation in the water cycle?','Energy from the Sun','Moonlight only','Magnetism','Where can water be stored between stages?','Notice one place water changes state today.'),
('dna','DNA and information','DNA carries biological information used by cells, although traits also depend on complex interactions and environment.','DNA is best described as…','A carrier of biological information','A type of planet','A metal','Why are traits not always simple?','Remember: genes influence traits, but environment can matter too.'),
('microbes','Microorganisms','Microorganisms include bacteria, fungi, protozoa and microscopic algae; many are useful, while some can cause disease.','Which statement about microbes is accurate?','Many are useful and some cause disease','All microbes are harmful','Microbes are visible without magnification','Where do useful microbes help humans?','Think of curd, bread or decomposition as microbial activity.'),
('energy','Energy transformation','Energy changes form—for example, electrical energy can become light, heat or motion.','A fan mainly converts electrical energy into…','Motion','Mass','Gravity','Why track energy transformations?','Identify two energy changes in one appliance.'),
('atoms','Atoms','Atoms are tiny units of matter made of smaller particles, and they combine in different ways to form substances.','Water is made from…','Atoms combined into molecules','Only light','No matter at all','Why can the same elements form different substances?','Look at a chemical formula and identify its element symbols.'),
('ecosystems','Ecosystems','An ecosystem includes living organisms and their interactions with air, water, soil and other non-living factors.','Which belongs to an ecosystem?','Organisms plus their environment','Only animals','Only soil','Why can removing one species matter?','Sketch a tiny food relationship among three organisms.'),
('sound','Sound waves','Sound is produced by vibrations and travels through a medium as a wave.','Sound begins with…','Vibration','Stillness','Vacuum energy','Why is there no ordinary sound in a vacuum?','Touch your throat gently while humming and notice vibration.')]),
('roots','Roots & India','ROOTS & INDIA',[
('aryabhata','Aryabhata','Aryabhata wrote the Aryabhatiya in 499 CE, covering mathematics and astronomy.','Aryabhata is especially associated with…','Mathematics and astronomy','Steam engines','Modern photography','What does his work illustrate?','Link historical achievement with the methods—observation and calculation—that made it possible.'),
('placevalue','Place-value mathematics','Indian mathematical traditions played a major role in developing and transmitting decimal place-value notation, including the use of zero as a number.','In a place-value system, the value of a digit depends on…','Its position','Its colour','Its handwriting style','Why is place value powerful?','Write 505 and explain why the two 5s have different values.'),
('nalanda','Nalanda','Nalanda in present-day Bihar became a major centre of learning in the first millennium CE and attracted scholars from different regions.','Nalanda is remembered primarily as…','A historic centre of learning','A modern airport','A seaport','What makes a learning centre influential?','Name one thing a great learning community needs besides buildings.'),
('sushruta','Sushruta tradition','The Sushruta Samhita is an important historical Sanskrit medical text associated with surgical knowledge and medical practice.','The Sushruta Samhita is linked to the history of…','Medicine and surgery','Navigation satellites','Printing presses','How should historical medical knowledge be studied today?','Respect historical context while separating it from modern clinical evidence.'),
('stepwells','Stepwells','Stepwells in parts of India combined water access, architecture and adaptation to seasonal conditions.','Stepwells were primarily connected with…','Water access and storage','Space travel','Ocean navigation','What design lesson can stepwells offer?','Look for how architecture responds to climate and local needs.'),
('indus','Indus urban planning','Cities of the Indus civilisation are known for planned streets, drainage systems and standardized construction features.','A notable feature of many Indus cities was…','Planned drainage','Skyscraper elevators','Railway stations','Why does drainage matter to a city?','Observe how water leaves a street or building during rain.'),
('oceantrade','Indian Ocean trade','For centuries, ports around the Indian Ocean connected South Asia with Africa, West Asia and Southeast Asia through trade and cultural exchange.','Indian Ocean trade connected India with…','Multiple regions across Africa and Asia','Only one nearby village','No overseas regions','What travels besides goods in trade networks?','Think of ideas, languages and technologies that can travel with people.'),
('literature','Classical literature','India’s literary traditions include works in Sanskrit, Tamil, Pali, Prakrit and many other languages across long periods.','India’s literary past is best described as…','Multilingual and diverse','Written in only one language','Entirely modern','Why does language diversity matter?','Learn one word from an Indian language different from your own.'),
('ironpillar','Metallurgy and the Iron Pillar','The Iron Pillar in Delhi is notable for its ancient ironworking and unusual resistance to corrosion.','The Iron Pillar is often discussed in relation to…','Metallurgy','Marine biology','Aeronautics','What should we study in historical technology?','Ask what materials, processes and environment produced the result.'),
('architecture','Temple architecture','Indian temple architecture developed diverse regional forms, materials and engineering solutions over centuries.','Temple architecture in India is…','Regionally diverse','Identical everywhere','Made only from wood','What can architecture reveal about a society?','Notice how material, climate, craft and belief shape a building.'),
('textiles','Textiles and dyes','Indian cotton textiles and dyeing traditions were historically traded widely and influenced global markets.','Indian textiles were historically important in…','Regional and global trade','Only private diaries','Space missions','What makes a craft economically important?','Look at one fabric and identify material, pattern and method.'),
('ecology','Traditional ecological knowledge','Communities across India developed local knowledge about water, crops, forests and seasons; such knowledge should be studied alongside modern evidence.','Traditional ecological knowledge is most responsibly approached by…','Studying context and testing evidence','Accepting every claim automatically','Rejecting all tradition automatically','How can old and new knowledge interact?','Compare one local practice with what modern science says about it.')]),
('math','Maths & Logic','MATHS & LOGIC',[
('primes','Prime numbers','A prime number greater than 1 has exactly two positive factors: 1 and itself.','Which number is prime?','13','15','21','Why are primes important in patterns and computing?','Find the next prime number after 20.'),
('fractions','Fractions','Fractions represent parts of a whole or ratios between quantities.','Which fraction equals one half?','3/6','2/3','4/5','Why can different fractions represent the same value?','Find two fractions equivalent to 1/4.'),
('percent','Percentages','Percent means “per hundred,” making it useful for comparing proportions.','25% is equal to…','1/4','1/3','3/4','Where do percentages appear daily?','Estimate 10% of one price without a calculator.'),
('ratio','Ratios','A ratio compares quantities using division or relative size.','If red:blue is 2:3, then for 4 red you need…','6 blue','5 blue','8 blue','Why are ratios useful in recipes and maps?','Double a simple recipe ratio mentally.'),
('patterns','Patterns','Recognizing a rule in a sequence helps predict later terms, but the rule must fit all known terms.','What comes next in 2, 4, 8, 16…?','32','18','20','Why can several rules fit a short sequence?','Invent two different patterns beginning 1, 2, 3.'),
('chance','Chance','For equally likely outcomes, probability can often be computed as favourable outcomes divided by total outcomes.','Probability of heads on a fair coin is…','1/2','1/3','1','Why does repeating trials help reveal patterns?','Flip a coin ten times and compare results with expectation.'),
('geometry','Geometry','Geometry studies shapes, sizes, positions and spatial relationships.','The angles in a triangle add to…','180°','90°','360°','Where does geometry appear in design?','Find three different triangles around you.'),
('mentalestimate','Mental estimation','Rounding numbers can make quick approximate calculations easier.','49 × 21 is closest to…','1000','100','10000','When is an estimate enough?','Estimate the total cost of three everyday items.'),
('average','Averages','The arithmetic mean is the sum of values divided by the number of values.','Mean of 2, 4 and 6 is…','4','3','6','Why can an average hide differences?','Compare two sets with the same mean but different spread.'),
('algebra','Algebra','Algebra uses symbols to represent unknown or variable quantities and relationships.','If x + 5 = 12, x is…','7','17','5','Why are variables useful?','Write an expression for “three more than a number.”'),
('coordinates','Coordinates','Coordinates locate points using ordered values along axes.','In (3, 2), the first number usually gives…','Horizontal x-position','Vertical y-position','Distance from origin only','Where are coordinates used outside maths?','Locate one point on a simple x-y grid.'),
('logic','Logical implication','A valid logical conclusion must follow from the stated premises, not from extra assumptions.','All squares are rectangles. This shape is a square. Therefore it is…','A rectangle','A circle','Not a polygon','Why separate premises from assumptions?','Write one “if…then…” statement and test its logic.')]),
('build','Build & Create','BUILD & CREATE',[
('algorithm','Algorithms','An algorithm is a clear sequence of steps for solving a problem or completing a task.','Which best describes an algorithm?','Ordered steps','A random guess','A decorative colour','Why must steps be unambiguous?','Write a three-step algorithm for making a cup of tea or water.'),
('prototype','Prototypes','A prototype is an early model used to test an idea before building the final version.','Why build a prototype?','To learn quickly from a small test','To guarantee perfection','To avoid feedback','What can a low-cost prototype reveal?','Sketch a paper prototype for one app screen.'),
('debug','Debugging','Debugging means finding, understanding and fixing errors in a system or program.','A good first debugging step is…','Reproduce the problem','Change everything at once','Hide the error','Why change one thing at a time?','When something fails today, write the exact steps that caused it.'),
('constraints','Design constraints','Constraints such as cost, time, safety and size shape what solutions are practical.','A design constraint is…','A limit a solution must respect','A guaranteed reward','An unrelated opinion','How can constraints improve creativity?','Solve one small problem using only materials already available.'),
('users','User needs','Good design starts by understanding the people who will use the solution and the job they need done.','Before designing, what should you learn first?','User needs','Favourite logo colour only','Your own assumptions only','Why observe users?','Ask one person what frustrates them about an everyday task.'),
('iteration','Iteration','Iteration means making a version, testing it, learning and improving the next version.','Iteration is best described as…','Build → test → improve','Build once and never change','Copy without testing','Why is feedback useful?','Improve one small thing after receiving feedback.'),
('robotics','Robotics','Robots combine sensing, computation and action to perform tasks in the physical world.','A robot sensor mainly helps it…','Detect information about its environment','Increase screen brightness only','Create gravity','Why do robots need feedback?','Identify a sensor you have seen in a phone, car or appliance.'),
('circuits','Making circuits','Simple electronic projects combine power, conductors and components such as LEDs, switches and resistors.','What should come first when building a circuit?','A safe plan and correct connections','Random wiring','Maximum voltage','Why is electrical safety non-negotiable?','Draw a simple battery-switch-light circuit before building it.'),
('data','Using data','Data becomes useful when it is collected carefully, organized and interpreted in context.','Which improves data quality?','Consistent measurement','Changing the method each time','Deleting inconvenient values','Why record units?','Measure the same quantity three times using the same method.'),
('story','Storytelling','A strong explanation often has a clear beginning, problem, evidence and conclusion.','What helps an idea become memorable?','Clear structure','More jargon','No conclusion','Why does audience matter?','Explain one concept in 30 seconds to someone younger.'),
('teamwork','Team creation','Teams work better when roles, goals and communication are clear.','A useful team habit is…','Agree on who owns what','Assume someone else will do it','Hide problems','Why surface disagreements early?','Before a group task, define one owner for each next action.'),
('safety','Maker safety','Building safely means identifying hazards, using tools correctly and stopping when conditions are unsafe.','What should you do before using an unfamiliar tool?','Learn the safe procedure','Guess','Remove protective equipment','Why does safety enable creativity?','Name one hazard before starting your next hands-on activity.')]),
('future','Future & Careers','FUTURE & CAREERS',[
('aerospace','Aerospace engineering','Aerospace engineers work on aircraft, spacecraft, propulsion, structures, controls and related systems.','Which subjects strongly support aerospace engineering?','Physics and mathematics','Only handwriting','Only memorization','Would you like to explore how flight and space systems work?','Try one short problem about forces or motion.'),
('ai','Artificial intelligence','AI work can involve mathematics, programming, data, model design, evaluation, safety and domain knowledge.','Which skill is useful in AI?','Logical problem solving','Ignoring data quality','Avoiding mathematics completely','Would you enjoy building systems that learn patterns from data?','Learn one basic Python data operation.'),
('medicine','Medicine and healthcare','Healthcare careers include medicine, nursing, diagnostics, public health, therapy, biomedical engineering and many other roles.','Healthcare work most directly combines science with…','Care for people','Avoiding communication','No teamwork','Would you enjoy solving health problems with science and empathy?','Learn how one organ system works.'),
('energycareer','Clean energy','Clean-energy careers span solar, wind, batteries, grids, materials, policy, finance and engineering.','Which challenge matters in renewable energy systems?','Storing and delivering energy reliably','Making energy disappear','Avoiding measurement','Would you like to work on cleaner energy systems?','Compare the energy sources used in your region.'),
('agritech','Agricultural technology','Agri-tech combines farming knowledge with sensors, data, biology, machinery and supply-chain innovation.','Agri-tech can use sensors to…','Measure field conditions','Stop all weather','Replace every farmer automatically','Would you like to solve food and farming problems with technology?','Identify one challenge between farm and consumer.'),
('cyber','Cybersecurity','Cybersecurity protects systems, networks and data through technical controls, good processes and human awareness.','Which habit supports cybersecurity?','Unique strong passwords','Sharing OTPs','Reusing one password everywhere','Would you enjoy investigating how systems can fail securely?','Enable multi-factor authentication on an important account.'),
('designcareer','Design','Design careers can combine research, visual thinking, systems, products, services and human behaviour.','Good design begins with…','Understanding the problem and user','Adding decoration first','Avoiding feedback','Would you enjoy turning user problems into better experiences?','Redesign one confusing everyday instruction.'),
('research','Research','Researchers ask focused questions, use methods to gather evidence and communicate what the evidence supports.','A research question should be…','Clear and testable where possible','Impossible to define','Answered before investigation','Would you enjoy investigating questions whose answers are not obvious?','Write one question you could investigate with data.'),
('entrepreneur','Entrepreneurship','Entrepreneurship involves identifying a real problem, creating value, testing assumptions and building a sustainable model.','A strong startup idea usually starts with…','A real problem worth solving','A logo only','A random trend','Would you enjoy building something people choose to use?','Interview one person about a problem before proposing a solution.'),
('infrastructure','Infrastructure','Infrastructure careers help design and operate transport, water, buildings, energy and digital systems used by communities.','Which is infrastructure?','Water supply network','A private diary','A single pencil','Would you like to improve systems used by millions of people?','Observe one public system and note one improvement idea.'),
('climatecareer','Climate solutions','Climate-related careers span science, adaptation, engineering, conservation, finance, policy and data.','Climate adaptation means…','Preparing for climate impacts','Pretending impacts do not exist','Stopping all weather','Would you like to work on resilience and environmental solutions?','Find one local climate risk and one adaptation response.'),
('teaching','Teaching and learning','Teaching combines subject knowledge, communication, empathy, assessment and the ability to help others learn.','An effective teacher needs…','Understanding plus communication','Only speed','No feedback','Would you enjoy helping others understand difficult ideas?','Teach one concept to a friend using an example.')]),
('values','Values & Character','VALUES & CHARACTER',[
('responsibility','Responsibility','Responsibility means owning your duties, choices and their consequences.','Which action shows responsibility?','Completing an agreed task without being chased','Blaming someone else immediately','Hiding unfinished work','When does responsibility matter most?','Finish one small promised task today before being reminded.'),
('honesty','Honesty','Honesty means representing facts and your own actions truthfully, even when truth is uncomfortable.','If you make a mistake, honesty means…','Acknowledge it accurately','Invent an excuse','Change the story','Why does honesty build trust?','Correct one small mistake instead of hiding it.'),
('empathy','Empathy','Empathy is the effort to understand another person’s perspective and feelings without assuming they are identical to yours.','A good first step in empathy is…','Listen carefully','Interrupt quickly','Assume motives','How can empathy improve disagreement?','Ask one genuine question before giving advice.'),
('courage','Courage','Courage is acting according to values despite fear or difficulty; it is not the absence of fear.','Which best describes courage?','Doing the right thing despite fear','Never feeling nervous','Taking every risk','Where is quiet courage useful?','Speak up respectfully about one small issue that matters.'),
('discipline','Discipline','Discipline is choosing useful actions consistently, especially when motivation is low.','Discipline is strongest when…','Good habits continue without constant motivation','You wait to feel inspired','You avoid routines','How do systems support discipline?','Set a five-minute start time for one task you have delayed.'),
('gratitude','Gratitude','Gratitude means noticing and appreciating help, opportunities or good things without ignoring real problems.','A practical gratitude habit is…','Thank someone specifically','Pretend everything is perfect','Expect help silently','Why be specific when thanking someone?','Send one sincere thank-you message today.'),
('humility','Humility','Humility includes recognizing what you know, what you do not know and what you can learn from others.','Humility in learning means…','Being willing to revise your view','Pretending to know everything','Never asking questions','How can humility strengthen expertise?','Say “I don’t know yet” once when that is the truthful answer.'),
('patience','Patience','Patience is the ability to stay constructive while progress, answers or results take time.','Patience is not the same as…','Doing nothing forever','Staying calm','Allowing learning time','Where does patience improve learning?','Stay with one difficult problem for two extra minutes.'),
('service','Service','Service means contributing time, skill or effort to improve something for others or the community.','Which is an act of service?','Helping solve a shared problem','Seeking credit only','Creating extra work for others','How can skills become service?','Use one skill to help someone without expecting a reward.'),
('respect','Respect','Respect means recognizing another person’s dignity, boundaries and right to be heard.','A respectful disagreement includes…','Critiquing the idea without insulting the person','Mocking the person','Refusing to listen','What does listening signal?','Let someone finish their point before responding.'),
('perseverance','Perseverance','Perseverance means continuing purposeful effort while adjusting strategy when necessary.','Perseverance differs from stubbornness because it…','Allows strategy to change','Never learns','Repeats failure blindly','When should you change approach?','Try a second method on one problem instead of quitting.'),
('fairness','Fairness','Fairness means applying relevant rules consistently while considering legitimate differences in circumstances.','Fairness always means…','Using relevant and consistent standards','Giving everyone identical outcomes regardless of context','Favouring friends','Why can equality and fairness differ?','Before judging a situation, ask whether the same standard applies to everyone.')]),
('world','India & World','INDIA & WORLD',[
('constitution','Constitutional basics','India’s Constitution sets out the structure of government, fundamental rights and duties, and key principles of the republic.','A constitution primarily provides…','A framework for governance and rights','A weather forecast','A sports score','Why do rules for institutions matter?','Learn the difference between a right, a duty and a law.'),
('geography','India’s geography','India includes mountains, plains, plateaus, deserts, coasts and islands, creating major ecological and cultural diversity.','Which feature contributes to India’s geographic diversity?','Multiple landforms and climate zones','One uniform landscape','No coastline','How does geography influence livelihoods?','Connect one local food or occupation to geography.'),
('monsoon','Monsoon systems','The Indian monsoon is driven by large seasonal changes in atmospheric circulation and strongly affects water and agriculture.','The monsoon is best described as…','A seasonal wind and rainfall system','One single storm','A daily sea breeze only','Why does monsoon variability matter?','Track rainfall in your area for one week.'),
('languages','Languages of India','India is highly multilingual, with many language families, scripts and literary traditions.','India’s language landscape is…','Highly diverse','Completely uniform','Limited to one script','What can multilingualism enable?','Learn how to greet someone in another Indian language.'),
('regions','Regional diversity','Food, clothing, music, architecture and festivals vary widely across Indian regions while also influencing one another.','Regional culture in India is best understood as…','Diverse and interconnected','Identical everywhere','Unchanging forever','Why avoid stereotypes about regions?','Learn one fact about a state or union territory other than your own.'),
('trade','Global trade','Modern economies exchange goods, services, capital and knowledge through global supply chains.','A supply chain connects…','Steps from inputs to final users','Only shop signs','Only advertising','Why can events far away affect local prices?','Trace where one everyday product might have been made.'),
('interdependence','Global interdependence','Countries and communities are connected through trade, climate, technology, migration, health and information networks.','Interdependence means…','Actions in one place can affect others','Every country is isolated','No systems cross borders','Where do shared problems need cooperation?','Name one issue that cannot be solved by one city alone.'),
('transport','Transport networks','Roads, railways, ports, airports and public transit connect people and economic activity.','A transport network mainly improves…','Movement and connectivity','Photosynthesis','Gravity','What makes transport inclusive?','Observe one barrier that makes travel harder for some people.'),
('cities','Cities','Cities concentrate people, jobs, services and infrastructure, creating both opportunities and challenges.','A growing city must plan for…','Housing, mobility, water and services','Only taller signs','No waste management','Why do urban systems interact?','Choose one city problem and list two connected causes.'),
('foodsystems','Food systems','Food systems include farming, storage, transport, processing, markets, cooking and waste.','Food reaches consumers through…','Many connected stages','One isolated step','No transport','Where can food waste occur?','Notice one point where food could be saved from waste.'),
('environment','Shared environment','Air, rivers, forests, oceans and biodiversity cross administrative boundaries and often require cooperative management.','Why can river pollution affect multiple regions?','Water flows across boundaries','Rivers stay inside one street','Pollution disappears instantly','What does shared environment require?','Think of one resource that needs cooperation to protect.'),
('publichealth','Public health','Public health focuses on protecting and improving health across populations through prevention, systems and evidence.','Which is a public-health measure?','Vaccination programs','One person’s private hobby','A fashion trend','Why does prevention matter?','Identify one health measure that works better when many people participate.')]),
('life','Life Skills & Responsibility','LIFE SKILLS',[
('passwords','Digital security','Strong unique passwords and multi-factor authentication reduce the risk that one stolen credential compromises multiple accounts.','Which password habit is safest?','Use unique passwords','Reuse one password everywhere','Share passwords with friends','Why does MFA help?','Turn on multi-factor authentication for one important account.'),
('money','Money basics','A simple budget separates income, needs, wants, saving and planned spending.','A budget helps you…','Plan where money goes','Create unlimited money','Avoid all choices','Why distinguish needs from wants?','Track one day of spending, even if the amount is small.'),
('time','Time management','Time management works better when priorities are converted into specific next actions and protected time.','Which is more actionable?','Study chapter 2 from 7:00–7:25','Study sometime','Be more productive','Why schedule a start time?','Put one important task into a 20-minute calendar block.'),
('communication','Clear communication','Clear communication states the purpose, important facts and requested next action without unnecessary ambiguity.','A useful message should make clear…','What you need and by when','Only emotions','As many words as possible','Why confirm understanding?','End one request today with a clear next step.'),
('team','Teamwork','Good teamwork combines shared goals, clear roles, reliable follow-through and constructive feedback.','What prevents duplicated work?','Clear ownership','Everyone assuming','No plan','How can teams handle blockers?','Say early when you cannot complete an agreed task.'),
('emergency','Emergency awareness','In an emergency, personal safety comes first; follow local emergency guidance and seek trained help rather than taking unsafe risks.','What is the first priority in an emergency?','Immediate safety','Recording a video','Guessing medical treatment','Why know emergency contacts?','Save the appropriate local emergency number in your phone.'),
('sleep','Sleep','Regular sufficient sleep supports attention, learning, mood and physical health.','Sleep is important for…','Learning and recovery','Eliminating the need for food','Making time unlimited','Why does a consistent routine help?','Choose a realistic fixed wind-down time tonight.'),
('nutrition','Nutrition','Balanced eating includes appropriate amounts of diverse foods, hydration and attention to individual needs.','Which supports everyday nutrition?','Variety and balance','Only one food forever','Skipping water','Why is hydration easy to overlook?','Keep water available during your next study session.'),
('movement','Physical activity','Regular physical activity supports cardiovascular health, strength, mobility and mental wellbeing.','A practical activity habit is…','Move regularly in ways appropriate for you','Sit continuously all day','Exercise only once a year','Why do small routines matter?','Take a short walk or stretch break after focused study.'),
('media','Media literacy','Media literacy means checking sources, context, evidence and incentives before believing or sharing content.','Before forwarding a surprising claim, you should…','Verify it','Forward immediately','Remove the source','Why do emotional posts spread quickly?','Pause before sharing content that makes you instantly angry or excited.'),
('conflict','Conflict resolution','Constructive conflict resolution separates the problem from the person and looks for needs, facts and workable next steps.','During disagreement, what helps most?','Describe the issue without personal attack','Raise your voice','Assume bad intent','Why restate the other view?','Summarize the other person’s point before responding.'),
('goals','Goal setting','Useful goals connect a meaningful outcome with measurable progress and a clear next action.','Which is the best next action?','Solve five practice questions at 6 PM','Become perfect','Work harder somehow','Why break goals into actions?','Define one task you can finish in under 15 minutes.')])
]

cards=[]
for pslug,pname,label,topics in PILLARS:
    assert len(topics)==12, (pslug,len(topics))
    for topic in topics:
        slug,name,fact,question,correct,d1,d2,reflection,action=topic
        base={'pillar':pslug,'pillar_name':pname,'label':label,'topic':slug,'topic_name':name,'min_grade':6,'max_grade':12,'language':'en','active':True}
        variants=[
            ('quiz', {'title':question,'subtitle':'Choose quickly, then learn from the explanation.','options':[{'id':'a','label':correct},{'id':'b','label':d1},{'id':'c','label':d2}],'correct':'a','explain':fact}),
            ('reveal', {'title':name,'subtitle':'Tap to reveal one useful idea.','reveal':fact}),
            ('choice', {'title':reflection,'subtitle':f'Connect {name.lower()} to the way you think or act.','options':[{'id':'strong','label':'Yes — this strongly interests me'},{'id':'curious','label':'Curious — show me what people do'},{'id':'try','label':'I’d try a small activity first'},{'id':'unsure','label':'Not sure yet'},{'id':'later','label':'Not for me right now'}]}),
            ('action', {'title':action,'subtitle':f'A tiny action linked to {name.lower()}.','options':[{'id':'today','label':'I’ll try it today'},{'id':'already','label':'I already do this'},{'id':'learn','label':'I want to learn more'}]})
        ]
        for kind,payload in variants:
            guid=str(uuid.uuid5(NS,f'{pslug}:{slug}:{kind}'))
            card={**base,'id':guid,'kind':kind,**payload}
            if pslug=='future' and kind=='choice': card['aggregate']='future_interest'
            cards.append(card)

assert len(cards)==432, len(cards)
assert len({c['id'] for c in cards})==432
OUT.parent.mkdir(parents=True,exist_ok=True)
OUT.write_text(json.dumps({'version':'2026.09.seed1','count':len(cards),'pillars':9,'cards_per_pillar':48,'cards':cards},ensure_ascii=False,separators=(',',':')),encoding='utf-8')
print(f'wrote {len(cards)} cards to {OUT}')
